### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by smallqiang** [Techprimate/TPPDF#108]
I jus use pod 'TPPDF' to install TPPDF. But an error was reported at compile time.
<img width="714" alt="error1" src="https://user-images.githubusercontent.com/926969/51165649-eaefcf80-18db-11e9-8501-afecefa61163.png">
<img width="629" alt="error2" src="https://user-images.githubusercontent.com/926969/51165653-edeac000-18db-11e9-9a90-514f65e93193.png">
In the file PDFGraphics.

**Comment by techprimate-phil** [comment]
What Swift version are you using and please provide the given error

**Comment by smallqiang** [comment]
> What Swift version are you using and please provide the given error

My project is used Swift4. And I have changed the TPPDF to Swift4.2. It's ok now. However, each pod update needs to be modified manually.

**Comment by techprimate-phil** [comment]
Consider a Cocoapods post install script like the following:

```
post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'TPPDF'
                target.build_configurations.each do |config|
                    if config.name == 'Debug'
                        config.build_settings['SWIFT_VERSION'] = '4.2'
                    end
                end
            end
        end
    end
```
