### ISSUE TITLE
'PDFPageLayout' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by EliteTechnicalCare** [Techprimate/TPPDF#111]
'PDFPageLayout' initializer is inaccessible due to 'internal' protection level. I attempted to initialize it myself as needed in Swift 4 to no avail. 

I am getting this error when simply setting up PDFPageLayout:
` let layout = PDFPageLayout()`

**Comment by techprimate-phil** [comment]
Hi, I changed the initialiser to be publicly accessible in an update of PR #110 
Can you please check it out and let me know if this resolves your issue!

**Comment by EliteTechnicalCare** [comment]
Works great for me! Thanks a bunch. I tried initializing it the same way you did but kept throwing strange OBJ-C errors... guess a solid Xcode restart and your code fixed it
