### ISSUE TITLE
[Question] How can I determine the number of pages

### ISSUE THREAD

**Issue by EliteTechnicalCare** [techprimate/TPPDF#116]
Two questions:
1. How can I determine the number of pages
2. Is there any donation links for your team. TPPDF has saved us so many hours of work we would love to pay it forward.

**Comment by techprimate-phil** [comment]
1. The number of pages is currently an internal variable of `PDFGenerator` and is set during calculations. Therefore we could add a readonly public accessor which is available after generating the document.
2. Thank you, we are glad to hear you like the project. We will check the solutions which are available for us a company and will come back to you. Do you have a preferred way of doing this?

**Comment by EliteTechnicalCare** [comment]
PayPal would work great. Also yea that sounds like it work perfectly

**Comment by techprimate-phil** [comment]
> Note: I added a PayPal Link in the [README](https://github.com/Techprimate/TPPDF#Contributors)

Looking at the code I realise that the `PDFGenerator` is an internal class only with the public static generator methods. Therefore we would have move from static generator methods to instances.
This seems like a major change.

See `PDFGenerator.generateURL` to see how the `PDFGenerator` is used.

**Comment by techprimate-phil** [comment]
I changed the `PDFGenerator` initialiser to be public, please see the `develop` branch.

You should be able to get the page count by using the following code:
```swift
let generator = PDFGenerator(document: document)
let _ = try? generator.createRenderObjects(progress: nil)
let count = generator.totalPages
```

**Comment by EliteTechnicalCare** [comment]
I think this should be on the main read me. Works perfect!
