### ISSUE TITLE
Pdf image scaling issue

### ISSUE THREAD

**Issue by harishthanniruios** [techprimate/TPPDF#118]
It seems when  selects pictures to upload in the mobile app, they progressively scale to be larger and larger through out the generated PDF.

**Comment by harishthanniruios** [comment]
If I uploaded 9 images and I m showing them or printing the images while showing in a webview or printing the images the size of the image is increaseing.i already set the the size of the image while uploading. can u fix this issue. thanks.

**Comment by techprimate-phil** [comment]
Is the resolution of the images getting bigger, or are frames of each image larger?

**Comment by harishthanniruios** [comment]
if I upload 30 images last image size is fixed to the screen and the first image is too small in size not resolution issue.
@techprimate-phil thanks for the replay.

**Comment by harishthanniruios** [comment]
Hi frames of the image is increasing



Thanks for the replay.

**Comment by techprimate-phil** [comment]
please provide a code example to reproduce this behaviour

**Comment by techprimate-phil** [comment]
Closed due to inactivity
