### ISSUE TITLE
Footer line through footer text for all US paper sizes

### ISSUE THREAD

**Issue by magnas35** [Techprimate/TPPDF#12]
Whenever I use any of the US paper sizes the footer line runs through the footer text and page number.

I tried this in the example app that you supply with the download and the same thing happens. Image is for USLetter.

![tppdf](https://cloud.githubusercontent.com/assets/4201689/26621763/c7892774-45df-11e7-8013-048f38fe9d93.jpeg)

**Comment by Techprimate** [comment]
I assume the line always draws below its position, ignoring the upwards stacking direction. 

I will take a look at all issues in the upcoming days including this one.

**Comment by Techprimate** [comment]
Can you please provide the code you used, so I can reproduce this exact case.

**Comment by magnas35** [comment]
I was using the Example TPPDF that you supplied in the Github repo. In the ViewController file I changed the first line of the generatePDF() method to `let pdf = PDFGenerator(format: .usLetter, paginationContainer: .footerRight)` so that an American page size was used. This causes the error shown in the image above.

**Comment by techprimate-phil** [comment]
I am closing this issue now as it might be outdated and there has not been any activity. If you still need this issue to be invested, please create a new issue.
