### ISSUE TITLE
PDF image - Bad Quality

### ISSUE THREAD

**Issue by bmahe9** [techprimate/TPPDF#121]
Hi Philip,
Thank you for your wonderful library. This is so helpful for us in creating this new app.

I just want to ask if would it be possible to have a better the image quality on the table? Because when rendering in the pdf it turns blurry. I want the image quality to remain as such so it won't appear blurry.
Thank you in advance.

Due to security reasons, I am not able to share the original Image. PFA a sample image with which i am facing this issue.

Code I use,

```swift
let coverImage = PDFImage(image: UIImage(named: "Banner")!, quality: 1, options: [.resize])

//To find proportional width and height
let imageWidth: CGFloat = coverImage.image.size.width
let imageHeight: CGFloat = coverImage.image.size.height

let targetHeight: CGFloat = imageHeight/imageWidth

print("PdfWidth", pdf.layout.width)
print("PdfHeight", pdf.layout.height)
print("TargetHeight", pdf.layout.width*targetHeight)

print("ImageWidth", coverImage.image.size.width)
print("ImageHeight", coverImage.image.size.height)

coverImage.size = CGSize(width: pdf.layout.width, height: pdf.layout.width*targetHeight)
print("size", coverImage.size)
pdf.addImage(.contentCenter, image: coverImage)
```

Log value I get
```
PdfWidth 595.0
PdfHeight 842.0
TargetHeight 63.10606060606061
ImageWidth 2145.0
ImageHeight 227.5
size (595.0, 63.10606060606061)
```

![Artboard1](https://user-images.githubusercontent.com/33709311/54264255-abbac380-4598-11e9-8c3a-b62c935aa204.png)

**Comment by techprimate-phil** [comment]
Hi, I just merged #119 onto develop. Would you mind testing it out using the following code line:

```swift
PDFImage(image: UIImage(named: "Banner")!, quality: 1, options: [.none])
```

**Comment by bmahe9** [comment]
> ```swift
> PDFImage(image: UIImage(named: "Banner")!, quality: 1, options: [.none])
> ```

Type 'PDFImageOptions' has no member 'none'.

I got this error message. I have updated TPPDF Pod to 1.3.2.

Thanks

**Comment by techprimate-phil** [comment]
You need to use the `develop` branch in your Podfile
```
pod 'TPPDF', :git => 'https://github.com/techprimate/TPPDF.git', :branch => 'develop'
```

But I just released 1.3.3, so please try that version

**Comment by bmahe9** [comment]
I have updated my pod to v1.3.3, but i was facing the same issue.
When looking into file "PDFImage" option .none is missing? Is it okay to modify in the source file?

Thank you in Advance

**Comment by techprimate-phil** [comment]
This option is part of `PDFImageOption`
--> https://github.com/techprimate/TPPDF/blob/master/Source/Image/PDFImageOptions.swift

**Comment by bmahe9** [comment]
This may seem basic but irrespective of option .none present in PDFImageOptions.swift, I am not able to call it in my code. 

Also I am not able to find the reference of .none in PDFImage.swift

![Screen Shot 2019-03-13 at 3 47 35 PM](https://user-images.githubusercontent.com/33709311/54271583-ce080d80-45a7-11e9-825e-205b18c7106a.png)
![Screen Shot 2019-03-13 at 3 50 00 PM](https://user-images.githubusercontent.com/33709311/54271584-ce080d80-45a7-11e9-9427-9583a24f7b4d.png)
![Screen Shot 2019-03-13 at 3 50 38 PM](https://user-images.githubusercontent.com/33709311/54271585-cea0a400-45a7-11e9-975b-48a4adeb1b9f.png)


Please find the attached.
Am i missing something?

**Comment by techprimate-phil** [comment]
Seems like the SourceKit is outdated.

Have you tried the following:
- Delete your `DerivedData` folder
- `pod deintegrate` and `pod install`

**Comment by bmahe9** [comment]
Thank you so much, it works perfectly.
