### ISSUE TITLE
color background of section

### ISSUE THREAD

**Issue by elminawim** [techprimate/TPPDF#122]
First of all thanks a lot for this great work..

I'd like to ask if it possible to add background color for section column.. 

thanks

**Comment by techprimate-phil** [comment]
As of now, it is not possible.

One way of enabling this, would be adding a background color property to [PDFSectionColumn](https://techprimate.github.io/TPPDF/Classes/PDFSectionColumn.html) and during calculations it creates a rectangle on each page the section is placed.

PR's are welcomed

**Comment by elminawim** [comment]
Thank you very much for the quick reply ..
Can you explain more to me how to draw the rectangle on one third of the page in length ...
Can I type it over the rectangle?

**Comment by elminawim** [comment]
i try func addLineSeparator but when increasing the width the rectangular becomes trends ..

is there other way to make rectangular as background..


![Screen Shot 2019-03-20 at 12 41 11 PM](https://user-images.githubusercontent.com/29329028/54678436-d0b9b400-4b0d-11e9-912e-6a1ec681b86b.png)

**Comment by techprimate-phil** [comment]
This skewed line should be resolved due to #128 

Background of sections and shape rendering are currently not imported, I might propose an enhancement

**Comment by techprimate-phil** [comment]
@elminawim I created `PDFGroup` which also have the ability to add a dynamic shape to the background, or only a simple color.

For `PDFSectionColumn` I should be able to implement the same behaviour and I'll take another look at it

**Comment by philprime** [comment]
Branch for development: [`feature/122-section-background-color`](https://github.com/techprimate/TPPDF/tree/feature/122-section-background-color)

**Comment by philprime** [comment]
Implemented in release `2.1.0`
