### ISSUE TITLE
can make the image circular  not rectangular

### ISSUE THREAD

**Issue by elminawim** [techprimate/TPPDF#123]
can make the image circular  not rectangular

**Comment by techprimate-phil** [comment]
Hi, would be great if you could give some more detail.

Are you requesting an option to create round images or just round corner etc.?
Please provide some insight and examples how this should work

**Comment by elminawim** [comment]
yes id like to create round images.. if it posible

**Comment by techprimate-phil** [comment]
At the moment, it is not, but this might be a nice addition to `PDFImage`

**Comment by techprimate-phil** [comment]
This will be available in 1.4.0 which I am releasing today
