### ISSUE TITLE
Swift 5.0

### ISSUE THREAD

**Issue by StefaniOSApps** [techprimate/TPPDF#124]
Swift 5.0 ?

**Comment by techprimate-phil** [comment]
Downloading new XCode right now and I'll take a look at it today.
I will then release 1.4.0 soon

**Comment by techprimate-phil** [comment]
I created a feature branch, would be great to get some feedback.

Do you think we should release a major or minor update (2.0.0 or 1.4.0)? I am not entirely sure what would be [semver](https://semver.org/) comformant

**Comment by StefaniOSApps** [comment]
1.4.0 ...

**Comment by techprimate-phil** [comment]
Alright, I'll update the develop branch to Swift 5.0 as soon as Travis CI support osx_image 10.2.
Until then the Swift5 branch will be kept up to date with the develop branch

**Comment by techprimate-phil** [comment]
Resolved in release 1.4.0
