### ISSUE TITLE
UIImage.jpegData(compressionQuality:) has been replaced by 'UIImageJPEGRepresentation' 

### ISSUE THREAD

**Issue by Mariusz558** [techprimate/TPPDF#126]
Hello,

I've installed TPPDF and now I've got the error message: UIImage.jpegData(compressionQuality:) has been replaced by 'UIImageJPEGRepresentation'.

The problem is when I replace this method I've got another error message: UIImage doesn't have the method 'UIImageJPEGRepresentation'. I'm confused. Any idea how to fix this?

Cheers
Mariusz

**Comment by techprimate-phil** [comment]
Hi, what version of TPPDF are you using, and what Swift Version is your project build with?

**Comment by Mariusz558** [comment]
TPPDF 1.3.3, Swift version 4. 

I've tried to change the Swift version, but it breaks another pod that I'm using in my project.

**Comment by techprimate-phil** [comment]
Well, TPPDF uses Swift 4.2, so you need to set that version only for the TPPDF target in the Pods.xcodeproj. Maybe this code in your Podfile helps:

```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == "TPPDF"
                config.build_settings["SWIFT_VERSION"] = "4.2"
            end
        end
    end
end
```

**Comment by Mariusz558** [comment]
Great! Thanks! It works fine now.

**Comment by Mariusz558** [comment]
I'm closing this one.
