### ISSUE TITLE
addLineSeparator is slightly skewed

### ISSUE THREAD

**Issue by bigfish2001** [techprimate/TPPDF#128]
This issue is easiest to see if the width of the separator is > 5.0

The problem is in override func draw(generator: PDFGenerator, container: PDFContainer) of PDFLineSeparator class.  The End Point is set to:

          CGPoint(x: self.frame.maxX, y: self.frame.maxY)

I believe it should be :

          CGPoint(x: self.frame.maxX, y: self.frame.origin.y)

**Comment by techprimate-phil** [comment]
This is resolved and will be released soon. 

Thank you for your contribution!
