### ISSUE TITLE
Some images with caption drawn very small.

### ISSUE THREAD

**Issue by magnas35** [Techprimate/TPPDF#13]
Sometimes an image is drawn very, very small at the bottom of the page. This seems to happen if the  image has a caption but sometimes yes and sometimes no.

![tppdf](https://cloud.githubusercontent.com/assets/4201689/26716621/1bc9ad16-4772-11e7-8efc-92daa6705b5e.jpeg)

**Comment by Techprimate** [comment]
Looks like the image fits the rest height of the page.

Can you show me the portion of your code where you add the image?

**Comment by magnas35** [comment]
I populate the PDF via pdfSidecar Core Data objects that return either a text note or an image. I add a date to the image as a caption and also append some other caption text if the user has created it. The images are added in the populatePDF method in the switch statement.

[PDFCreator.swift.zip](https://github.com/Techprimate/TPPDF/files/1070805/PDFCreator.swift.zip)

**Comment by nemecence90** [comment]
Is this solved?

**Comment by techprimate-phil** [comment]
I am working on a TPPDF update right now, changing the whole library logic takes a lot of work, but it will be worth it. I am also going to address this issue!

**Comment by techprimate-phil** [comment]
I will close this for now, to finally get ready for the release of the update. If you still encounter this afterwards, please create another issue!
