### ISSUE TITLE
Version change log feature

### ISSUE THREAD

**Issue by omiz** [techprimate/TPPDF#131]
I was using an earlier version and updated to the latest version recently and I wanted to check the changes to see how they effect my project.

Where can I find the change log if it's already there or maybe is it possible to get some short bullet point list about the changes.

[this](https://help.github.com/en/articles/creating-releases)  is what I mean.

**Comment by techprimate-phil** [comment]
Hi thanks for the input.
Using Github Release functionality seems like a smart idea, I‘ll take a look at it.

Currently the whole changelog is documented in the [CHANGELOG.md](CHANGELOG.md)

**Comment by techprimate-phil** [comment]
Added the github releases for the 5 most recent verrsioins
