### ISSUE TITLE
Image in footer section is displaying beyond the page boundaries

### ISSUE THREAD

**Issue by dileepiscalling** [techprimate/TPPDF#132]
Complete information of this issue is present here - https://stackoverflow.com/questions/56056793/tppdf-ios-image-in-footer-section-is-displaying-beyond-the-page-boundaries

I have attached my sample project too.

My code snippet:

> var layout = PDFPageLayout()
> layout.margin = UIEdgeInsets(top: 30, left: 30, bottom: 30, right: 30)
> layout.size = PDFPageFormat.a4.size
> layout.space.header = 30
> let document = PDFDocument(layout: layout)
> 
> let headerImage = UIImage(named: "header")!
> let headerImageElement = PDFImage(image: headerImage)
> headerImageElement.quality = 1.0
> headerImageElement.options = [.none]
> document.addImage(.headerCenter, image: headerImageElement)
> 
> for i in 1...100 {
>     document.addText(.contentCenter, text: "Content goes here. \(i)")
> }
> 
> let footerImage = UIImage(named: "footer")!
> let footerImageElement = PDFImage(image: footerImage)
> footerImageElement.quality = 1.0
> footerImageElement.options = [.none]
> document.addImage(.footerCenter, image: footerImageElement)
> 
> do {
>     var docURL = try PDFGenerator.generateURL(document: document, filename: "Example.pdf")
>     let request = NSURLRequest(url: docURL);
>     webView.load(request as URLRequest);
> }
> catch {
>     print("error loading PDF")
> }
[Sample App.zip](https://github.com/techprimate/TPPDF/files/3161855/Sample.App.zip)

**Comment by techprimate-phil** [comment]
I took a look at it, and it seems there has been a calculation error for footer elements.

As i just refactored calculation portions, I think I might have fixed this too. Can you please take a look at the `develop` branch, test it using that branch and give me feedback if you can still reproduce the issue.

This is an example how you can use the develop branch in your Podfile:

```
pod 'TPPDF', :git => 'https://github.com/techprimate/TPPDF.git', :branch => 'develop'
```
