### ISSUE TITLE
how to add image to cell in table without changing height of cell

### ISSUE THREAD

**Issue by elminawim** [techprimate/TPPDF#133]
id lick to add image to cell in table but the cell is resize according to the height of the image ..

Can I resize image and Can I but fixed cell height for cell or for table?

thanks a lot for your time

**Comment by omiz** [comment]
This feature is currently unavailable but until it's added you can maybe resize the image by yourself 
here is a good article about image resizing https://nshipster.com/image-resizing/

**Comment by philprime** [comment]
Could this be fixed by the same logic as request in #158?

**Comment by philprime** [comment]
I'll close this in favor of #158
