### ISSUE TITLE
Is there a way to add multiple texts in a single line

### ISSUE THREAD

**Issue by dileepiscalling** [techprimate/TPPDF#134]
Something like :
**Age**: 35, **Gender**: Female, **Occupation**: Engineer.

I want to add 'age', 'gender', 'occupation' texts separately :
document.addText(text: "Age:")
document.addText(text: "35.")
document.addText(text: "Gender:")
document.addText(text: "Female.")

But i want all these to display side by side. 
If I add these in sections, I need to mention the width percentage which doesn't work when text to display is dynamic

**Comment by techprimate-phil** [comment]
if the words are directly linked like a sentence (just like your example) 
I would recommend to create a single Attributed String and then add it.

Otherwise use [multi-column-sections](https://github.com/techprimate/TPPDF#multi-column-sections)

**Comment by dileepiscalling** [comment]
Ok, I was using Attributed String actually.
