### ISSUE TITLE
Carthage TPPDF  1.4.0 doesn't work

### ISSUE THREAD

**Issue by turk-jk** [techprimate/TPPDF#135]
with 
`carthage update TPPDF`
 

it throws error
*** Skipped building TPPDF due to the error:
Dependency "TPPDF" has no shared framework schemes

thanks

**Comment by techprimate-phil** [comment]
I don't know why this keeps happening, Xcode messing up 😠 

Please try the fix at #98

**Comment by techprimate-phil** [comment]
Fixed with 1.4.1
