### ISSUE TITLE
how to start new page automatically when content is full

### ISSUE THREAD

**Issue by hitesh-shukla** [techprimate/TPPDF#136]
Hi there,

How can we start new page when content is full, is there any way to create new pages automatically according to centent

**Comment by techprimate-phil** [comment]
Hi,

what do you mean with "when the content is full"?
TPPDF adds page breaks automatically when the next element does not fit in a page any more

**Comment by techprimate-phil** [comment]
Closed due to inactivity, please reopen if still relevant

**Comment by dsk1306** [comment]
Hi @philprime, could you please tell me if `adds page breaks automatically` also works with attributed strings? I'm currently playing around with `2.4.1` and I'm struggling to make a PDF with a bunch of attributed strings that automatically breaks to a new page when needed.

**Comment by philprime** [comment]
@dsk1306 simple text and attributed text is handled internally as a `PDFAttributedTextObject` which converts the simple text into a `NSAttributedString`.

If it isn't working for you, please provide an example `PDFDocument` code snippet, so I can test your issue.
