### ISSUE TITLE
Create Example with all functions

### ISSUE THREAD

**Issue by Techprimate** [Techprimate/TPPDF#14]
Create a new example project with all methods.

**Comment by Techprimate** [comment]
Would be great if anybody finds some time to create a fully working example which uses all TPPDF features to create a document and creates a Pull Request!

**Comment by ArdaDinler** [comment]
thank you for this. I found 
attributedText.draw(in: CGRect(origin: frame.origin, size: CGSize(width: frame.width, height:frame.height + 20))) EXC_BAD_ACCESS code =  2

**Comment by Techprimate** [comment]
if this error is connected to the example, please explain the problem in detail.
If not create a new issue.
