### ISSUE TITLE
Swift package manager support?

### ISSUE THREAD

**Issue by pj4533** [techprimate/TPPDF#146]
I know the README says Swift package manager isn't support due to UIKit, but now that Swift PM has first class support in Xcode, it'd be nice to get rid of Cocoapods.  Any chance of getting support for SwiftPM in TPPDF?

**Comment by techprimate-phil** [comment]
Well I do not have enough experience with SwiftPM nor do I know how to support it, therefore I am open for PR from anybody interested in looking into it

**Comment by pj4533** [comment]
I took a quick look yesterday...I am no expert on SwiftPM either, but it isn't too difficult to support.  I think the main issue is re-architecting how the repo is structured so it can support SwiftPM and cocoa pods together.  But, I think my hopes of ditching Cocoapods is a bit pre-mature.  Most libraries don't support SwiftPM yet anyway, prob best to wait till the new Xcode ships.   Feel free to close this for now.

**Comment by philprime** [comment]
There is now a PR #164 but it is stale and does not pass any tests.

**Comment by philprime** [comment]
This is now supported, check pre-release version `2.0.0` and the master branch
