### ISSUE TITLE
How to remove header from Last page?

### ISSUE THREAD

**Issue by iharshb** [techprimate/TPPDF#147]
Thank you for the amazing library.

I just want to do one task where I can **hide/remove header part from the last page** or a particular page. Is it possible?

I have set a table in the header as per my requirement. Now on the last page, I don't want to table which available as a header in all pages.

**OR What I need** : If there is any callback where I know starting and ending of a particular page.

**Comment by techprimate-phil** [comment]
Are you writiing about table headers or page headers?

**Comment by iharshbhavsar** [comment]
I have added in page header.

**Comment by philprime** [comment]
So the header elements should be hidden/not be rendered on specific pages?

**Comment by philprime** [comment]
Closed due to inactivity, please reopen if necessary
