### ISSUE TITLE
PDFTable() header style not displayed same in all page

### ISSUE THREAD

**Issue by irfantai** [techprimate/TPPDF#148]
i have added PDFTable() to two types cell section and description
my issued is
if new page first cell is section then table header displayed style in section style
if new page first cell is description then table header displayed style in description style

i have added this code:

        let table = PDFTable()
        table.widths = [0.08, 0.40, 0.10, 0.07,0.07,0.20,0.08]
        table.padding = 2.0
        table.showHeadersOnEveryPage = true
        table.style.rowHeaderCount = 1
       table.style.columnHeaderCount = 1

**Comment by philprime** [comment]
This is affected by the PR #181 (and of the time of me writing this, headers on every page are WIP)

**Comment by philprime** [comment]
Should be resolved now, when TPPDF 2.0 is out, please use it and see if it happens
