### ISSUE TITLE
Advance page numbering/pagination

### ISSUE THREAD

**Issue by StefaniOSApps** [Techprimate/TPPDF#15]
Hi, 

First of all thank you for this beautiful framework.

Me and others would help very much if you could create an automatic page number.
Maybe like this:

pdf.addPageNumbering(.footerCenter, style: "Page %d of %d", fromPage: 1, toPage: 4)

... so without ", toPage: 4)" its generate from first to the laste Page.

Enjoy 👍

**Comment by Techprimate** [comment]
Hi,

Great idea! I always like to talk about new features.

But for clarification:
When adding pagination this way, it is a command which should be called once? Or do you need to enable pagination from 1 to 4, and afterwards you call the same command with 2 to 5, to have page 1-4 and 6-11 with pagination?

Maybe this gets too complicated as it is hard to tell how many pages willl be generated without doing big calculations, but I think there is a way of having great pagination.

If you want to we can use this thread to discuss how pagination should work in the future and what it can do (exclude pages, reset page counter...)

**Comment by StefaniOSApps** [comment]
I think, this command should be called once.

### This is my idea:
1. pdf.setPageNumbering(.footerCenter, style: "Page %d | %d", fromPage: 1, toPage: 4)
2. pdf.hidePageNumbering = [0,1,2] <- Array with hided PageNumberings
3. pdf.startPageNumberingWith = 2; 

(1.)  _Use Predefined Syles?_ maybe Roman numerals, or Numbers formatted by NumberFormatter
(3.) start with 2 on the first Page

**Comment by Techprimate** [comment]
1) We could extend the styling possibilities by defining defaults using a string enum just like your example, and even an closure getting page and total page count as parameter returning an attributed string.

2) so if we want to start with 1 on the third page we would set startPageNumberingWith = -1 and exclude pages 1 and 2?
We could add a method startAtPage(page: 3) for convenience.

**Comment by StefaniOSApps** [comment]
2. better: startAtPage(page: 3, with: 1)

**Comment by Techprimate** [comment]
Please checkout the latest develop branch.

**Comment by Techprimate** [comment]
Please check out the latest develop branch:
I created only the following method:

```swift
setPageNumbering(_ container: Container = Container.none, style: PaginationStyle = PaginationStyle.Default, from fromPage: Int = 0, to toPage: Int = Int.max, hiddenPages: [Int] = []) 
```

First it calculates the whole document (probably adding a caching mechanism soon) to calculate the total amount of pages. `from` and `to` are not page indicies but the page numbers. hiddenPages are an array of page numbers where pagination won't be rendered.

**Comment by StefaniOSApps** [comment]
okey - it's O.K. .. :-)

**Comment by davidseek** [comment]
why cant i find this? :/

**Comment by techprimate-phil** [comment]
@davidseek are you looking for the mentioned initializer or for the pagination?

**Comment by davidseek** [comment]
it was my bad. i used the master branch. it appears to be crazy outdated compared to the develop branch. 

with the develop branch i find all the desired cool shit

**Comment by techprimate-phil** [comment]
Good to hear that! 
And, yes I know, it is very outdated, but I had to rebuild the project as mentioned in #29 and I did not want to release a new version with not all the features from the old system. Work in progress!

**Comment by davidseek** [comment]
i get that. it is really an awesome project. i had to find something like that for a dev project and i think i have looked into pretty much all the available framework in swift and objC. i was about to give up and then found yours. 

highly appreciated and i will make sure to contribute where i can
