### ISSUE TITLE
Carthage Support is broken [1.5.3]

### ISSUE THREAD

**Issue by mbger** [techprimate/TPPDF#153]
At least on my end, Carthage can not build the framework for the latest release `1.5.3`.

The first error that came up was the missing shared scheme as described in #98. Unchecking and checking the box for the TPPDF scheme as described [in this comment](https://github.com/techprimate/TPPDF/issues/98#issuecomment-438402758) did fix the issue. 

However the framework still does not build due to a missing `.plist` file. Here's the error message when running `carthage build --verbose --platform "iOS" --no-skip-current TPPDF`:

    error: could not read data from '$(SRC_ROOT)/Carthage/Checkouts/TPPDF/Example/Pods/Target Support Files/TPPDF/TPPDF-Info.plist': The file “TPPDF-Info.plist” couldn’t be opened because there is no such file.

And indeed there is no such file; The actual directory contents are:

```
$ tree Target\ Support\ Files
                                                                                                                                                                                     
Target\ Support\ Files
├── Nimble
│   ├── Nimble-dummy.m
│   ├── Nimble-prefix.pch
│   ├── Nimble-umbrella.h
│   ├── Nimble.modulemap
│   └── Nimble.xcconfig
├── Pods-TPPDF_Example
│   ├── Pods-TPPDF_Example-acknowledgements.markdown
│   ├── Pods-TPPDF_Example-acknowledgements.plist
│   ├── Pods-TPPDF_Example-dummy.m
│   ├── Pods-TPPDF_Example-frameworks.sh
│   ├── Pods-TPPDF_Example-umbrella.h
│   ├── Pods-TPPDF_Example.debug.xcconfig
│   ├── Pods-TPPDF_Example.modulemap
│   └── Pods-TPPDF_Example.release.xcconfig
├── Pods-TPPDF_Tests
│   ├── Pods-TPPDF_Tests-acknowledgements.markdown
│   ├── Pods-TPPDF_Tests-acknowledgements.plist
│   ├── Pods-TPPDF_Tests-dummy.m
│   ├── Pods-TPPDF_Tests-frameworks.sh
│   ├── Pods-TPPDF_Tests-umbrella.h
│   ├── Pods-TPPDF_Tests.debug.xcconfig
│   ├── Pods-TPPDF_Tests.modulemap
│   └── Pods-TPPDF_Tests.release.xcconfig
├── Quick
│   ├── Quick-dummy.m
│   ├── Quick-prefix.pch
│   ├── Quick-umbrella.h
│   ├── Quick.modulemap
│   └── Quick.xcconfig
└── TPPDF
    ├── TPPDF-dummy.m
    ├── TPPDF-prefix.pch
    ├── TPPDF-umbrella.h
    ├── TPPDF.modulemap
    └── TPPDF.xcconfig
```

**Edit:** `1.4.1` fails with the same error message (missing `.plist` file). But the shared TPPDF scheme is present after checkout.

**Comment by techprimate-phil** [comment]
Hi, thanks for reporting.

I just checked and it seems like the Example has not the updated dependencies from version 1.5.3.
I am creating a hotfix, would you trying with the branch `hotfix/1.5.4`?

**Comment by mbger** [comment]
Thanks for looking into this so quickly! The fix does not work right out of the box. 

```
λ carthage update --platform "iOS" --verbose TPPDF
*** Fetching TPPDF
*** Checking out TPPDF at "9bd84f465fd9dc6e59b07ca244d751a967025e72"
*** Skipped building TPPDF due to the error:
Dependency "TPPDF" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/techprimate/TPPDF/issues/new

λ carthage build --platform "iOS" --no-skip-current --verbose TPPDF
*** Skipped building TPPDF due to the error:
Dependency "TPPDF" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/techprimate/TPPDF/issues/new
*** Skipped building DT-ForceMeter.iOS due to the error:
Dependency "DT-ForceMeter.iOS" has no shared framework schemes for any of the platforms: iOS
```

I'll try re-creating the scheme manually

**Comment by mbger** [comment]
For what it's worth: Trying to build the Pods project directly from within Xcode fails, too.

**Comment by techprimate-phil** [comment]
alright, first off I hope to fix the missing shared scheme once again (something in git ignore is not correct).

I also recreated the example project, tests run locally, waiting for CI

**Comment by mbger** [comment]
> ... (something in git ignore is not correct)

I never made a framework Carthage-ready so I kinda don't know what I'm talking about, but:

The `.gitignore` file lists `Example/Pods` as being excluded from version control. And over in #98 you mention that [you have to explicitly add files with the `--force` option](https://github.com/techprimate/TPPDF/issues/98#issuecomment-438402758). Maybe going the other way round (don't ignore `Example/Pods` and list all files to be excluded in `.gitignore` instead) might be a start.

**Comment by techprimate-phil** [comment]
That's true, but git should not ignore the file as it is explicitly excluded in the gitignore now.

Please try again, or let me know how to create a basic carthage test project (I never actually used in production)

**Comment by mbger** [comment]
55cf43392ec4ddff1fc371bd2b5d05338f8e3f9d fixes step 1 of the problem: I don't have to create the shared workspace manually! However, the build still fails because of the missing `TPPDF-Info.plist`.

**Comment by mbger** [comment]
> or let me know how to create a basic carthage test project

I'll see if I can make a bare project to reproduce the issue!

**Comment by mbger** [comment]
There you go: [`TPPDF-Carthage`](https://github.com/mbger/TPPDF-Carthage)

**Comment by techprimate-phil** [comment]
Thank you, I checked it out and looks like something is very wrong as I do get this error:

> Check dependencies
> The file “SwiftLint.xcconfig” couldn’t be opened because there is no such file. (/tmp/TPPDF-> Carthage/Carthage/Checkouts/TPPDF/Example/Pods/Target Support 
 Files/SwiftLint/SwiftLint.xcconfig)

I need to do some investigation

**Comment by techprimate-phil** [comment]
Alright, I added the file manually and changed the gitignore to be more precies.

Please try again with the hotfix

**Comment by mbger** [comment]
That fixed it for me. Thank you for the support!

**Comment by techprimate-phil** [comment]
Glad to hear that, going to merge and release it now
