### ISSUE TITLE
Table Object/Header on each new page

### ISSUE THREAD

**Issue by StefaniOSApps** [Techprimate/TPPDF#16]
Hey,

I have already said how beautiful is the framework? 👍 

You already know the problem, if you have a table, which goes over several pages. The head is only displayed on the first page.

my suggestion would be...

First, create a table as new Object:
var table = Table() <- CustomObject by TPPDF
... so you can (optional)
table.addData(...)
table.addStyle( )
table.addRow( )

but i need this:
table.addHeader(...)
table.showHeaderOnEachPage = true

and finaly:

pdf.addTable(table)

Thanks and Enjoy! 
Nice work!

**Comment by Techprimate** [comment]
I like the idea of creating a table object which holds all the data. 
This way it is easier to create a table, sending it to the generator as a command and it could also help to resolve issue #5 

I will give it a shot next week and let you know.

**Comment by Techprimate** [comment]
Please checkout commit #ae9d58e4172c437d4ece0108eb2cb850bcace81d https://github.com/Techprimate/TPPDF/commit/ae9d58e4172c437d4ece0108eb2cb850bcace81d

I created the table object and `showHeadersOnEveryPage` as a property. 

Let me know your thoughts
