### ISSUE TITLE
Add an HTML within attribute tag to document object and then draw it to PDF context

### ISSUE THREAD

**Issue by nckien** [techprimate/TPPDF#161]
Hi admin,
This is best tool to draw text, images.... into PDF file.
It would be great if TPPDF can draw html within tag attributes 
Thank you

**Comment by philprime** [comment]
Hi there, we have talked about this issue before, so I will propose my solution again here (for everyone else):

TPPDF is not a HTML Parsing library, it is only a PDF Creation library.
Therefore I recommend using some framework made for parsing HTML code and writing a Adapter to TPPDF.
If there is a high demand for this kind of feature, let me know in this issue and I might create a subproject
