### ISSUE TITLE
Async PDF Generation

### ISSUE THREAD

**Issue by EliteTechnicalCare** [techprimate/TPPDF#162]
When generating large pdfs (for example I am attempting to generate a 4,700ish page pdf with images, it currently takes an obscene amount of time like 1-2 hours easily). I noticed the main UI thread is doing all the heavy lifting and it would be far faster (and wouldn't lock up the UI!) if you used grand central dispatch or other forms of concurrent processing. 

This can also prevent crashing from memory related issues.

**Comment by techprimate-phil** [comment]
TPPDF is a single thread engine, therefore I did not add any background-thread processing.

**Comment by philprime** [comment]
Have you tried running the calculations in the background using `Dispatch`?
The updated examples (on `develop`) are using the same principle, as I did not add async generation to TPPDF (yet)

**Comment by philprime** [comment]
@EliteTechnicalCare what Async options should TPPDF support? I am currently thinking about

1. Callback
2. Using the process object
3. Using the [Combine](https://developer.apple.com/documentation/combine) framework, unfortunately not available before iOS 13

**Comment by krjw-eyev** [comment]
I think people should implement this themselves.

This is a quick example how this could look like:
```
    func generatePDFAsync(finished: @escaping (Data?) -> ()) {
        let dgroup = DispatchGroup()
        var pdf: Data? = nil
        DispatchQueue.global(qos: .background).async { // use different qos dpending on prioity
            dgroup.enter()
            let doc = generatePDF() // this is the call where you do all the stuff
            pdf = PDFGenerator(document: doc).generateData()
            dgroup.leave()
        }
        dgroup.notify(queue: .main) {
            // finished - use pdf to do something...
            finished(pdf)
        }
    }
```

**Comment by philprime** [comment]
Fascinating, I haven't used `DispatchGroup` before.

I am also uncertain if this should be part of the main framework.
Instead I am thinking about creating another framework TPPDFAsync, which only extends TPPDF by different async approaches. Therefore devs can use TPPDF as usual and if they want a common async functionality they find it there

**Comment by krjw-eyev** [comment]
I think that is a great idea! It would be easier to maintain and with SPM including other packages is pretty easy.

**Comment by philprime** [comment]
I just created [TPPDFAsync](https://github.com/techprimate/TPPDFAsync) and pushed a version 0.0.1 to Cocoapods and SPM support. Carthage has some issues as it has nested dependencies.
It is a very basic first version offering Combine Tasks and Dispatch Callbacks.

Further development/issues will be on that repository
