### ISSUE TITLE
TableStructureInvalid

### ISSUE THREAD

**Issue by TCzerny** [techprimate/TPPDF#163]
Hi I'm unable to generate any kind of table. (tested with 1.5.4, 1.4.1 and 1.3.0)
I've tried it with my own tabledata first but then also using the example from the readme.

I always getting the error: 
- TableStructureInvalid
- Data and alignment for row with index 0 does not have the same amount!

error is thrown at:

```swift
let url = try PDFGenerator.generateURL(document: document, filename: filename, progress: {...}
```

No error in the catch of the table.generateCells()

```swift
do {
    try table.generateCells(data: [
            [1, "Name", "Image", "Description"],
            [2, test, test, "test"]
        ],
        alignments: [
            [.center, .left, .center, .right],
            [.center, .left, .center, .right]
        ])
```

**Comment by philprime** [comment]
Can you please provide me a full reproducible example?

**Comment by philprime** [comment]
As of the upcoming new API of `PDFTable` this issue should not arise anymore.
Please checkout the `feature/41-tables-spanning` branch.

In the new API you can use subscripts to manipulate table data, and you do not have to rely on `generateCells` anymore.

**Comment by meesum-Ali** [comment]
@philprime I am having the same issue. Although counts of data and alignments are same but still when generate URL or data method is getting called it is throwing the same exception as mentioned by @TCzerny. I am using swift 4.2 and TPPDF 1.3.3

**Comment by philprime** [comment]
@meesum-Ali can you try the pre-release version 2.0.0 and see if it still occurs? As of 2.0.0 you do not need to use generateCells anymore

**Comment by philprime** [comment]
Due to inactivity I would like to close this issue. I do not have the time to support versions prior to Swift 5.2, I am sorry.
If this issue still occurs with the 2.X versions, please reopen this issue

**Comment by meesum-Ali** [comment]
@philprime sure. Will reopen if the issue persist in new releases. Thank you for the cooperation.
