### ISSUE TITLE
Spacing between list items 

### ISSUE THREAD

**Issue by JaiDeves** [techprimate/TPPDF#168]
Hi,

I've created PDFList using a few PDFListItem.
I need to set vertical spacing between each item.

How can i achieve that?

**Comment by philprime** [comment]
Hi there,

this is not implemented yet. I think it should be easy to add the necessary properties to `PDFList` to create your desired behaviour.

This has no priority yet, therefore I can't tell you when it is implemented.
But feel free to add the functionality on your own and open a Pull Request

**Comment by philprime** [comment]
Hi @JaiDeves,

as this enhancement request still exists, I was wondering if you still need it?
And if so, how would you want to use it, same spacing between all elements, or configurable per element?

**Comment by philprime** [comment]
Closed due to inactivity

**Comment by icopano** [comment]
I opened a PR to address this @philprime, let me know what you think 😋
it was my first ever open source contribution, so I apologise in advance if I have skipped some procedure. https://github.com/techprimate/TPPDF/pull/352
