### ISSUE TITLE
Add clickable image

### ISSUE THREAD

**Issue by diptiganatra** [techprimate/TPPDF#170]
I want to add images which should be clickable and redirect to given link.

**Comment by techprimate-phil** [comment]
Hi, sounds like a good idea.
Maybe this can be implemented as a "object attribute".
Also this seems to be related to #71

**Comment by diptiganatra** [comment]
@techprimate-phil Thanks for your support. I'm trying to solve this from your suggestion of issue #71 but not getting the solution. Also I don't see any "object attribute" in the code.

**Comment by techprimate-phil** [comment]
You are correct, the "object attributes" do not exist.

That's just a more generic approach similar to HTML attributes (there might be other future attributes, such as in-document links).
My idea is the following:

- Create any kind of PDFObject (e.g. PDFImageObject based on a PDFImage)
- Calculate the frame of it
- Render it
- If a link attribute is given, add a clickable area using the link using the frame of the object

**Comment by philprime** [comment]
I actually just created an implementation on `feature/170-clickable-objects`, going to merge it on develop right now

**Comment by diptiganatra** [comment]
Thank you very much @philprime . Temporarily I had implemented clickable image by overlapping a clear coloured link on Image. But that was working just for iOS. If I share that PDF in android device, it was not working. Today I implemented enhanced version of TPPDF and it works like charm now. Thank you so much :)
