### ISSUE TITLE
how to show the pdf in the swift view

### ISSUE THREAD

**Issue by basmaamahmoud** [techprimate/TPPDF#173]

**Comment by philprime** [comment]
Hi, please give a description on what you are asking for and what your current code is

**Comment by basmaamahmoud** [comment]
I want to show the table in pdf in view controller before printing it,
and how can i add image to header and footer of the pdf page  
        
        let table = PDFTable()
        
                let str = String(format: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.")
                let str1 = String(format: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \nLorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. \n\nIt has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ")
        
        
                do {
                
                   try table.generateCells(
                        data:[
                            [NSLocalizedString("ClientName", comment: ""), NSLocalizedString("Evaluation", comment: ""), NSLocalizedString("NoOfEvaluations", comment: "")],
                            ["project.name" + "\n" +  "project.address1", UIImage(named: "pdfMarker")!, str],
                            ["project.name" + "\n" +  "project.address1", UIImage(named: "pdfMarker")!, str1]
                        ],
                        alignments: [
                            [.topLeft, .top, .top],
                            [.topLeft, .top, .top],
                            [.topLeft, .top, .top]
                   ])

                    
                    
                    } catch PDFError.tableContentInvalid(let value) {
                        // In case invalid input is provided, this error will be thrown.

                        print("This type of object is not supported as table content: " + String(describing: (type(of: value))))
                    } catch {
                        // General error handling in case something goes wrong.

                        print("Error while creating table: " + error.localizedDescription)
                    }

        table.widths = [
                   0.23, 0.30, 0.47
               ]

            let style = PDFTableStyleDefaults.simple
        table.style = style

        do {
            // Style each cell individually
            try table.setCellStyle(row: 1, column: 0, style: PDFTableCellStyle(colors: (fill: UIColor.lightGray, text: UIColor.black)))
            try table.setCellStyle(row: 1, column: 1, style: PDFTableCellStyle(colors: (fill: UIColor.lightGray, text: UIColor.black)))
            try table.setCellStyle(row: 1, column: 2, style: PDFTableCellStyle(colors: (fill: UIColor.lightGray, text: UIColor.black)))
            try table.setCellStyle(row: 2, column: 0, style: PDFTableCellStyle(colors: (fill: UIColor.lightGray, text: UIColor.black)))
            try table.setCellStyle(row: 2, column: 1, style: PDFTableCellStyle(colors: (fill: UIColor.lightGray, text: UIColor.black)))
            try table.setCellStyle(row: 2, column: 2, style: PDFTableCellStyle(colors: (fill: UIColor.lightGray, text: UIColor.black)))
        } catch PDFError.tableIndexOutOfBounds(let index, let length){
            // In case the index is out of bounds

            print("Requested cell is out of bounds! \(index) / \(length)")
        } catch {
            // General error handling in case something goes wrong.

            print("Error while setting cell style: " + error.localizedDescription)
        }
        table.padding = 1.0
        table.margin = 2.0

        table.showHeadersOnEveryPage = true

        let document1 = PDFDocument(format: .a4)
        
        document1.add(table: table)

**Comment by basmaamahmoud** [comment]
ad this for the header of page
![Screen Shot 2019-12-19 at 5 20 31 PM](https://user-images.githubusercontent.com/35192412/71185525-4660d500-2284-11ea-8b99-437f74c41586.png)

add this for the footer of page
![Screen Shot 2019-12-19 at 5 20 37 PM](https://user-images.githubusercontent.com/35192412/71185567-5973a500-2284-11ea-9147-3655821556ef.png)

**Comment by philprime** [comment]
One option is using a a UIWebView (checkout the example):

```swift
@IBOutlet weak var webView: UIWebView!
[...]
let url = try generator.generateURL(filename: "Example.pdf")
// Load PDF into a webview from the temporary file
self.webView.loadRequest(URLRequest(url: url))
```
Another (newer) approach is using PDFKit:

https://developer.apple.com/documentation/pdfkit

**Comment by basmaamahmoud** [comment]
thanx a lot
