### ISSUE TITLE
Hyperlink in pdf document?

### ISSUE THREAD

**Issue by cameron-erdogan** [techprimate/TPPDF#178]
Is there a way to insert a hyperlink into a PDFDocument? Doesn't seem to be the case based on the documentation but perhaps I missed something.

**Comment by philprime** [comment]
Hi there,
one way of achieving it is using NSAttributedString and adding a link attribute (see #71). 
I actually just implemented Hyperlink support using NSAttributedString two days ago, therefore it is only available on the `develop` branch for now.

If you are able to use pre-release software, feel free to use the develop branch
