### ISSUE TITLE
Get Problem in NSMutableAttributedString

### ISSUE THREAD

**Issue by Bikram786** [Techprimate/TPPDF#18]
I try with this pdf.addAttributedText(.contentCenter, text: title) and not get the content in Center. Always showed the content Left side. Please help me.

**Comment by nemecence90** [comment]
Make the text center for attributed string too

```
let style = NSMutableParagraphStyle()
style.alignment = NSTextAlignment.center

let title = NSMutableAttributedString(string: "Hello World", attributes: NSAttributedStringKey.paragraphStyle: style ])
```

**Comment by techprimate-phil** [comment]
Should be fixed now, as there was a content positioning error
