### ISSUE TITLE
Blank page at the end of each batched document (external document)

### ISSUE THREAD

**Issue by EliteTechnicalCare** [techprimate/TPPDF#180]
I am currently using the 'develop' branch in order to test adding external PDFs. While the functionality is running great I keep running into an issue were a blank page is added in the end after importing an external document.

Here is what I am using
` batchPagesv2.add(externalDocument: PDFExternalDocument(url: url, pages: pages[count]))`

Whats interesting is that if I duplicate the batch job multiple times, only one extra blank page is added on the end. If I do not use external documents there is no blank page added either. So I am a bit lost as to where this page is coming from.

So either this can be flagged as a bug or a feature suggestion to maybe make a boolean to filter out blank pages upon generation.

**Comment by philprime** [comment]
I might have an idea what's going on:

When adding the external document, it adds a page break afterwards, so the new page starts after the external document page. Also a new page is started when merging multiple PDFDocuments, therefore there is an another page break added afterwards.
Seems like it should not add the page break after an external document, if there is no more content in the PDFDocument.

In case you want to further debug it (until I get some time on my hand), this might be the code in question: https://github.com/techprimate/TPPDF/blob/develop/Source/Internal/External/PDFExternalDocumentObject.swift

**Comment by EliteTechnicalCare** [comment]
I am working on final preparations for the launch of my app this weekend, but once I submit it to apple ill def will give it a go. Before you added merging pdfs I added a bit of a hack solution by storing the PDF as a global variable and just adding to it so similarly I had issues with extra pages that I had to resolve (and did)

**Comment by philprime** [comment]
The idea of specifying pages is more control on which pages to include from a file.
e.g. it's a 400 pages e book and I only want to add a single page.

But we could add improvements, such as an empty array includes all pages, or mixing single pages with ranges etc.
If that is necessary, please open up another enhancement issue about that topic

**Comment by philprime** [comment]
@EliteTechnicalCare are you able to give me a small code sample to reproduce the exact issue?

**Comment by EliteTechnicalCare** [comment]
Sorry for the long pause, the way the current init is set up is messed me up regarding the pages. Because it is asking for an Int vs a closedRange (ie 1...5). So I assumed that setting the pages to say 6, would print all 6 pages vs ONLY page 6. Only thing I would maybe change is allow a closed range or let the pages be optional and do all pages if nil. Ill open a separate issue on that because I had some ideas for improvement/created several other methods.




> I might have an idea what's going on:
> 
> When adding the external document, it adds a page break afterwards, so the new page starts after the external document page. Also a new page is started when merging multiple PDFDocuments, therefore there is an another page break added afterwards.
> Seems like it should not add the page break after an external document, if there is no more content in the PDFDocument.
> 
> In case you want to further debug it (until I get some time on my hand), this might be the code in question: https://github.com/techprimate/TPPDF/blob/develop/Source/Internal/External/PDFExternalDocumentObject.swift

As for this, commenting out the code below worked flawlessly. My personal opinion, I would just remove it, its very easy to add a page break if adding additional stuff, or maybe make it a variable in the function if you want an extra page in the end.

`result += try PDFPageBreakObject().calculate(generator: generator, container: .contentLeft)`

**Comment by EliteTechnicalCare** [comment]
> @EliteTechnicalCare are you able to give me a small code sample to reproduce the exact issue?

I am literally just doing this: 
` batchPagesv2.add(externalDocument: PDFExternalDocument(url: url, pages: pagesRange))`
batchpagesv2 being the name of my PDFDocument. Thats the only thing causes the extra page.

**Comment by EliteTechnicalCare** [comment]
Another possible idea would be the ability to remove a page. like pdf.removePage or something like that.

**Comment by philprime** [comment]
Could you create a pull request for the develop branch with your proposed fix?

**Comment by EliteTechnicalCare** [comment]
> I might have an idea what's going on:
> 
> When adding the external document, it adds a page break afterwards, so the new page starts after the external document page. Also a new page is started when merging multiple PDFDocuments, therefore there is an another page break added afterwards.
> Seems like it should not add the page break after an external document, if there is no more content in the PDFDocument.
> 
> In case you want to further debug it (until I get some time on my hand), this might be the code in question: https://github.com/techprimate/TPPDF/blob/develop/Source/Internal/External/PDFExternalDocumentObject.swift

So the issue is this line:
` result += try PDFPageBreakObject().calculate(generator: generator, container: .contentLeft)`

Commenting out fixes the problem. Additionally if you want you could add a bool "addPageBreak" and just wrap the above line in an if statement. That should be far easier than removing a page.

**Comment by philprime** [comment]
removing a page is fairly difficult, as the calculations are dynamic, therefore you can't be sure which page an element is on.

As for commenting out the line, this might work for you case, but it will not work for others, when adding normal content after an external page

**Comment by EliteTechnicalCare** [comment]
> removing a page is fairly difficult, as the calculations are dynamic, therefore you can't be sure which page an element is on.
> 
> As for commenting out the line, this might work for you case, but it will not work for others, when adding normal content after an external page

I figured as such, I think a better solution would be to either an overloaded function or simply add an additional input ie:

`pdfDocument.add(externalDocument: PDFExternalDocument(url: url, pages: pagesRange, addPageBreak: false))`

That way users can easily decide if they need a page break at the end or not. 

**OR**

Comment out that line entirely because users can easily add 
'createNewPage()'
But cannot easily delete a page

**Comment by philprime** [comment]
That would be a manual way, for sure.

I mean, it could also perform it on a smart way. If an external document is inserted, it should add a page break, but only if the next element is not another external document

**Comment by EliteTechnicalCare** [comment]
I think it should only add a page break **IF** the next element is not an external document **AND** another element exists.

The issue right now is it's adding a blank page, even though there are no additional elements, so users printing out documents always have to deal with a blank page at the end of the document. This is further compounded if multiple external documents are stitched together.

**Comment by philprime** [comment]
this sounds correct, I created a possible fix on the `develop` branch. 
Can you please check it out and let me know if it behaves correctly

**Comment by philprime** [comment]
I just released `2.0.0`, where this should be fixed.
Please confirm this assumption

**Comment by philprime** [comment]
@EliteTechnicalCare anything new on my fix?

**Comment by philprime** [comment]
As I think this should be fixed now, I will close this issue for now. If it still occurs with the latest version, please reopen the issue.
