### ISSUE TITLE
Image quality from UIImage to PDFImage is pixilated

### ISSUE THREAD

**Issue by AlexLojewski** [techprimate/TPPDF#182]
I save a image with imagePicker:

```swift
if let image = imageView.image {
    let documentsDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
    let fileName = "Logo.jpg"
    let fileURL = documentsDirectory.appendingPathComponent(fileName)
    if let data = image.jpegData(compressionQuality: 1.0) {
        try! data.write(to: fileURL)
        imagePath = fileURL.absoluteString
    } else {
        AlertView.showAlertView(with: "Bild speichern...", and: "Es trat ein unerwarteter Fehler auf. Bitte versuchen sie es nochmals gegebenenfalls mit einem anderen Logo als JPG Datei.", in: self)
        imagePath = "FALSE"
    }
}
```

and when i create a pdf with this image is the image pixilated:
```swift
//LOAD LOGO IMAGE

let paths = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)
let documentsDirectory = paths[0]
let fileManager = FileManager.default
let imagePath = documentsDirectory + "/Logo.jpg"
var logo = UIImage()
if fileManager.fileExists(atPath: imagePath) {
    logo = UIImage(contentsOfFile: imagePath)!
}
let logoImage = PDFImage(image: logo,size: CGSize(width: 415, height: 95), quality: 1.0)
```

I testet with bigger size over 415px and with a image with the exact size from 415px 95px
The solution is ever the same with the quality

What is my mistake in the code?

Alex

**Comment by philprime** [comment]
Hi there, thanks for posting the issue as requested by me.

As I can see you are not setting any `options` on the `PDFImage`.
The default options are `[.resize, .compress]` and therefore I think that might be the issue.

- `.resize` scales the image down using the given `quality` value
- `.compress` actual flags the image to be compressed using JPEG and the given `quality` value

Can you please try the following line:
```swift
let logoImage = PDFImage(image: logo,size: CGSize(width: 415, height: 95), options: .none, quality: 1.0)
```

**Comment by AlexLojewski** [comment]
I have a issue with this error:

`Incorrect argument labels in call (have 'image:size:options:quality:', expected 'image:caption:size:sizeFit:quality:options:cornerRadius:')`

`Replace 'size: CGSize(width: 415, height: 95), options: .none, quality' with 'caption: CGSize(width: 415, height: 95), size: .none, sizeFit'`

`let logoImage = PDFImage(image: logo, size: CGSize(width: 415,  height: 95), options:  .none, quality: 1.0)`

**Comment by AlexLojewski** [comment]
I have solved the problem with the size with this code and options:

`let logoImage = PDFImage(image: logo, caption: nil, size: CGSize(width: 500, height: 60), quality: 1.0, options: .none, cornerRadius: .none)`

thank you for your help
