### ISSUE TITLE
Extract pages from a PDF document

### ISSUE THREAD

**Issue by raphaklr** [techprimate/TPPDF#183]
Is it possible to extract PDF pages from a document? Let‘s say I have a document with 6 pages and I want to generate a new document that just contains pages 1-3?

**Comment by philprime** [comment]
One option would be generating the document with 6 pages and then generating another document where the first one is included using `PDFExternalDocument`.

`PDFExternalDocument` is currently only on `develop`

**Comment by raphaklr** [comment]
So you basically mean something like that?

```swift
let urlToSixPagesDoc = ...
let threePagesDocument = PDFExternalDocumentObject(url: urlToSixPagesDoc, pages: [1,2,3])
```

**Comment by philprime** [comment]
yes, but the first document would have to be generated first.

**Comment by raphaklr** [comment]
Thank you, I will try that. Will close this for now.
