### ISSUE TITLE
Attributed String is not working with PDFTableCell

### ISSUE THREAD

**Issue by vimal-bhadra** [techprimate/TPPDF#185]
Hello,
I want to display hyperlink with text. So I used attributed string. It is not working with PDFTableCell.

Please review following code :
let content = PDFTableContent(type: .attributedString, content: content)
let cell = PDFTableCell(content: content, alignment: alignment)

So can you please help me ?

**Comment by philprime** [comment]
Are you using the develop branch?

**Comment by vimal-bhadra** [comment]
We are using pod.
pod 'TPPDF'

**Comment by philprime** [comment]
Hyperlinks are not released yet (see the [CHANGELOG](https://github.com/techprimate/TPPDF/blob/develop/CHANGELOG.md) on develop)

Therefore to use this feature you would have to use the `develop` branch, which contains unstable code. Please see here how to do that:
http://guides.cocoapods.org/using/the-podfile.html

**Comment by vimal-bhadra** [comment]
Hello
It is working fine with below code
let title = NSMutableAttributedString(string: "\(txt)", attributes: [
                                .foregroundColor:  UIColor.blue,
                                .link: "http://www.google.com"
])

But getting crash with below code
let title = NSMutableAttributedString(string: "\(txt)", attributes: [
                                .foregroundColor:  UIColor.blue,
                                .link: "http://www.google.com",
                                .underlineStyle: NSUnderlineStyle.single
])

Getting crash at : PDFCalculations.swift
internal static func calculateTextFrameAndDrawnSizeInOnePage(frame: CGRect,
                                                                 text: CFAttributedString,
                                                                 currentRange: CFRange) -> (CGRect, CTFrame, CGSize) {
        let framesetter = CTFramesetterCreateWithAttributedString(text)
}

How do I give underline to text ?
Please help me

**Comment by philprime** [comment]
Hi there, I just released 2.0.0 where this is could be resolved.
Please take a look and let me know if it is still an issue

**Comment by philprime** [comment]
@vimal-bhadra anthing new on this issue?

**Comment by philprime** [comment]
I'll close this for inactivity. If it's still relevant with the newest TPPDF version, please reopen
