### ISSUE TITLE
How can in PDFTable() add a PDFSimpleText()

### ISSUE THREAD

**Issue by AlexLojewski** [techprimate/TPPDF#186]
Hello,

i want to add a PDFSimpleText with Style in a PDFTable(). But it doesnt work with this example:

`let tableHeaderStyle = document.add(style: PDFTextStyle(name: "tableHeaderStyle", font: UIFont.boldSystemFont(ofSize: 6), color: UIColor.black))`

`let typeTable = PDFSimpleText(text: "Text with Style", spacing: 2, style: tableHeaderStyle)`

` let table = PDFTable()
        
        do{
            try table.generateCells(
                data:
                [
                    [nil, nil, nil, nil],
                    ["\(typeTable)", "Typ: 000000", "Year: 1990", "Hours: 125"]
            ],
                alignments:
                [
                    [.left, .left, .left, .left],
                    [.left, .left, .left, .left]
            ])
        } catch {
            AlertView.showAlertView(with: "Error", and: error.localizedDescription, in: self)
        }`

I have no error but in the generated file stand: PDFSimpleText<0x00006000003e2f... with Optional(TPPDF.PDFTextStyle

Is there a possibility for this issue?

Alex

**Comment by philprime** [comment]
As of now you could use cell styles for styling https://github.com/techprimate/TPPDF#cell-style
