### ISSUE TITLE
Watermark Image

### ISSUE THREAD

**Issue by Bikram786** [Techprimate/TPPDF#19]
How I can set Watermark Image on each page of PDF.

**Comment by techprimate-phil** [comment]
Try this:

Create your watermark as an image with transparency. 
Then create your document and overlay its content using the `setContentOffset` method.

Currently doing the offset calculations might be hard, but I am working on the 1.0.0 release of TPPDF where calculations will be before rendering and therefore it is possible to get more data.

**Comment by AlasKuNull** [comment]
How I can set Watermark Image on each page of PDF.
i need help how to do this.
thanks a lot.
