### ISSUE TITLE
Getting error in Table rendering

### ISSUE THREAD

**Issue by meesum-Ali** [techprimate/TPPDF#192]
While adding data to table and table to document. When using "PDFGenerator.generateURL", getting exception.
▿ PDFError
  ▿ tableStructureInvalid : 1 element
    - message : "Data and alignment for row with index 0 does not have the same amount!"

error is on following line:
`let url  = try PDFGenerator.generateURL(document: document, filename: "Account-Statement.pdf")`

I am using release 1.3.3 and swift 4.2

```
let transactionDataArray = getTransactionsDataArray(wrappingQuotes: "")
let alignments = transactionDataArray.map { $0.map { _ in PDFTableCellAlignment.left }}
try table.generateCells(data: transactionDataArray,
                                    alignments: alignments)
document.addTable(table: table)
```

**Comment by philprime** [comment]
Hi there, would you mind to checkout the new Table api and logic from the develop branch I am about to release?

**Comment by meesum-Ali** [comment]
Sure. Let me look into that.

**Comment by philprime** [comment]
It is Swift 5.2

You may also want to try the new subscript syntax for tables, as I am trying to deprecate the `generateCells` method in favor of it

**Comment by meesum-Ali** [comment]
Will try it as of now my code base is on swift 4.2

**Comment by philprime** [comment]
@meesum-Ali anything new on this issue?

**Comment by meesum-Ali** [comment]
Hey @philprime still pending at my side because my code base is still on swift 4.2. Actually we are having issues with VoIP notifications and so cannot upgrade our codebase. Will inform you as soon as I get to know if it is fixed.

**Comment by meesum-Ali** [comment]
@philprime the issue is existing till version 1.6. For now unable to update to swift 5.2 and cannot check the latest version. Any solution for Swift 5 ?

**Comment by philprime** [comment]
I am sorry, I do not have the time to support older versions of Swift 5
