### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by kerekson** [techprimate/TPPDF#193]

**Comment by philprime** [comment]
Hi there, this would require a rewrite, as TPPDF is build on top of UIKit, which is iOS only

**Comment by EliteTechnicalCare** [comment]
As a note it appears to work fine when used with Project Catalyst

**Comment by philprime** [comment]
@EliteTechnicalCare that's great news.

I took a closer look, and it might be possible to combine AppKit & UIKit, as both are build on top of CoreGraphics, which is the foundation of TPPDF

**Comment by philprime** [comment]
Progress is in branch [`feature/193-macos-support`](https://github.com/techprimate/TPPDF/tree/feature/193-macos-support)

**Comment by philprime** [comment]
Compilation is successful, but there are calculation errors that still need to be fixed

**Comment by philprime** [comment]
PR #217 is working now, will merge into develop soon, creating next minor release afterwards

**Comment by philprime** [comment]
Released in 2.2.0
