### ISSUE TITLE
Our App Uses TPPDF

### ISSUE THREAD

**Issue by EliteTechnicalCare** [techprimate/TPPDF#196]
Just wanted to let you know we finally launched our app on the App Store and heavily use TPPDF for all our PDF needs. 

Our Link:
https://apps.apple.com/us/app/etc-practice-manager/id1125247333

**Comment by philprime** [comment]
That's awesome! Thank you for letting us know!

If you wish, you can create a Pull Request to add your App Icon to the [list](https://github.com/techprimate/TPPDF#apps-using-tppdf)

**Comment by philprime** [comment]
Might have closed this too soon (in case you didn't see my response)

**Comment by EliteTechnicalCare** [comment]
Saw it, will do
