### ISSUE TITLE
Carthage update failed (Xcode 11.4.1)

### ISSUE THREAD

**Issue by shawn736** [techprimate/TPPDF#197]
Xcode: 11.4.1
When i use "carthage update --platform iOS --no-use-binaries" to update, an error is reported.
How to fix it ? 
```
Building scheme "Nimble" in TPPDF.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/xxxxx/Desktop/xxxxxx/Carthage/Checkouts/TPPDF/Example/TPPDF.xcworkspace -scheme Nimble -configuration Release -derivedDataPath /Users/xxxxx/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4.1_11E503a/TPPDF/1.6.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/_n/bzkm4xnd6513ntkzhghq6cnr0000gn/T/TPPDF SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/xxxxx/Desktop/xxxxxx/Carthage/Checkouts/TPPDF)
```

**Comment by philprime** [comment]
Hi there, what branch are you using?

**Comment by shawn736** [comment]
> Hi there, what branch are you using?

In the Cartfile file: 
`"github "techprimate/TPPDF" ~> 1.4"`

**Comment by philprime** [comment]
Would you mind to test the develop branch, I have been testing Carthage integration yesterday (with some struggles) and it might resolve your case

**Comment by shawn736** [comment]
> Would you mind to test the develop branch, I have been testing Carthage integration yesterday (with some struggles) and it might resolve your case

I have tested the develop branch. Carthage update is ok , but there is an error in this code.
`let url = try? PDFGenerator.generateURL(documents: documents, filename: "\(name).pdf")`
The error is :
`Extra argument 'documents' in call
Instance member 'generateURL' cannot be used on type 'PDFGenerator'; did you mean to use a value of this type instead?`

**Comment by philprime** [comment]
Oh yes, as it is WIP I changed from a static generator approach to an instance approach. 
Checkout the `PDFMultiDocumentGenerator.swift`, documentation: https://github.com/techprimate/TPPDF/tree/develop#multiple-documents

**Comment by shawn736** [comment]
> Oh yes, as it is WIP I changed from a static generator approach to an instance approach.
> Checkout the `PDFMultiDocumentGenerator.swift`, documentation: https://github.com/techprimate/TPPDF/tree/develop#multiple-documents
OK, thank you for your help

**Comment by shawn736** [comment]
> Oh yes, as it is WIP I changed from a static generator approach to an instance approach.
> Checkout the `PDFMultiDocumentGenerator.swift`, documentation: https://github.com/techprimate/TPPDF/tree/develop#multiple-documents

OK， thank you for your help.
