### ISSUE TITLE
Page break after space

### ISSUE THREAD

**Issue by albanotmakolli** [techprimate/TPPDF#204]
The content won't be put to a next page automatically if it won't fit because of an added space

**Comment by philprime** [comment]
Can you please provide an example code for me to reproduce

**Comment by albanotmakolli** [comment]
I have a table that can span on multiple pages, and then after the table I have a few sections and plain text. Between the sections and plain texts I am adding spaces using `document.add(space:)`. If the page ends with a space then the rest of the content isn't shifted to the next page automatically. 

You can test this with simpler cases, e.g. on the TextExampleFactory. Just add 
`
        document.add(space: 300)
`, `
        document.add(text: "Test text here")
`
before the `return [document]` and the test text won't appear.
I got a workaround which works for now where I'm adding blank text with a font size of the space I need.

**Comment by philprime** [comment]
Thanks for the detailed description!

I created a fix on `develop`, please check it out and let me know if it works for you too!
The issue was, `PDFSpaceObject` did not add a page break when it hit the page end, as the text calculations didn't detect the negative height

**Comment by albanotmakolli** [comment]
The fix works fine! Thank you for your swift response

**Comment by philprime** [comment]
great! I'll release 2.0.1 now
