### ISSUE TITLE
PDFImage Scaling without Considering Caption Height

### ISSUE THREAD

**Issue by chrisgonzgonz** [techprimate/TPPDF#208]
Hi, 

Big fan of this project, thank you for your work. 

When creating a `PDFImage` with a caption, the caption height does not seem to be included in image scaling/sizing calculations. This results in a page break between image and caption when the image is large and I'm using `PDFImageSizeFit.width`. 

I noticed this [TODO](https://github.com/techprimate/TPPDF/blob/848d33ac5801547eccf9dd6bacb2330d6c783a21/Source/Internal/Utils/PDFCalculations.swift#L460) so I've submitted a PR for your consideration.

### Relevant Details
- Swift 5
- TPPDF 1.6.0

### Sample Image
![IMG_5244](https://user-images.githubusercontent.com/4155953/84588490-01f17300-ae7c-11ea-9d69-56aff4288a40.JPG)

# Examples
# Before Patch
<img width="859" alt="Pasted_Image_6_14_20__20_19" src="https://user-images.githubusercontent.com/4155953/84588554-79bf9d80-ae7c-11ea-80e8-89947bc567eb.png">

--------------------------------------------------------------------------------

# After Patch
<img width="1035" alt="Pasted_Image_6_14_20__20_21" src="https://user-images.githubusercontent.com/4155953/84588574-b8555800-ae7c-11ea-8f8e-21f69ccb17a9.png">

**Comment by philprime** [comment]
Amazing, thanks for your effort!

I will need a few days but I will take a look at it for sure!

**Comment by philprime** [comment]
Thanks a lot again, I merged your changes to the master and I am releasing 2.1.2 right now!

**Comment by chrisgonzgonz** [comment]
Awesome, glad I could help. Thanks again @philprime !
