### ISSUE TITLE
EXC_BAD_ACCESS (code =2) CRASH 

### ISSUE THREAD

**Issue by ArdaDinler** [Techprimate/TPPDF#21]
When I create PDF inside  in DispatchQueue as shown below
NOT: dates and values string array, macId -> string (Array store 6000 data for each dates and values)

DispatchQueue.global(qos: .utility).async {
                                    
        let pdf = PDFGenerator(format: .a4)
        
        var tableAlignment: [[TableCellAlignment]] = [
            [.center, .center, .center, .center]
        ]
        
        var tableData: [[String]] = [
            ["",Localization("dateTitle"),Localization("deviceIdTitle"),Localization("temperatureTitle")]
        ]
        for index in 0...dates.count - 1
        {
            tableData.append([String(describing:(index+1)),dates[index],macId!,values[index]])
            tableAlignment.append([TableCellAlignment.center, TableCellAlignment.center, TableCellAlignment.center, TableCellAlignment.center])
        }

        let tableWidth: [CGFloat] = [
            0.08, 0.35, 0.40, 0.17
        ]
        
        
        pdf.setFont(font: UIFont.systemFont(ofSize: 10))
        pdf.addTable(data: tableData, alignment: tableAlignment, relativeColumnWidth: tableWidth)
        let currentDateTime = Date()
        let formatter = DateFormatter()
        formatter.dateFormat = "dd-MM-yyyy,HH:mm:ss"
        let dateString = formatter.string(from: currentDateTime)
        
        let url = pdf.generatePDFfile("logger_"+dateString)
                                    
        DispatchQueue.main.async {
               // now update UI on main thread
        }
                                    
}

I got an error 

PDFGenerator.swift class inside drawTable func (lines between 506-513)

        for (rowIdx, row) in dataInThisPage.enumerated() {
            for (colIdx, text) in row.enumerated() {
                let frame = framesInThisPage[rowIdx][colIdx]
                let attributedText = NSAttributedString(string: text, attributes: attributes)
                // the last line of text is hidden if 30 is not added
           ->>>>(This line)     attributedText.draw(in: CGRect(origin: frame.origin, size: CGSize(width: frame.width, height:frame.height + 20)))
            }
        }

**Comment by nemecence90** [comment]
Hi, @ArdaDinler, Did you find any solution for this? I am getting the same crash. I know the source, this crash happens when you addText to PDF.

**Comment by techprimate-phil** [comment]
On the develop branch, this method does not exist anymore, and whole text rendering is moved into `PDFAttributedTextObject` therefore I am closing this.

If you find this on the develop branch or in the future release again, please open another issue.
