### ISSUE TITLE
Documentation Link Broken?

### ISSUE THREAD

**Issue by grantespo** [techprimate/TPPDF#219]
In the ReadMe, when I click the Documentation link, it redirects me back to the original repo (stays on same page)

**Comment by philprime** [comment]
Does it open the GitHub pages? https://techprimate.github.io/TPPDF/ ?

**Comment by philprime** [comment]
So i guess the index.html page should be fixed with the redirect, but I do have issues with the usage.md

**Comment by philprime** [comment]
Okay so I guess I fixed it, it is currently running on [Travis](https://travis-ci.org/github/techprimate/TPPDF/builds/703902997), then the new documentation will be published
