### ISSUE TITLE
Error in paper size definition

### ISSUE THREAD

**Issue by Sgkhour** [techprimate/TPPDF#225]
Hi, i was trying to debug an issue with lack of space around the footer of a page when i think i found the culprit . in **PDFPageFormat+SizeConstants.swift**, the page size defined is incorrect. 

more specifically the **height** of **usLetter** 
` return CGSize(width: 612, height: 762)   // 216  x 279  mm | 8.5  x 11.0 in`
should be 792 (11x72) instead
` return CGSize(width: 612, height: 792)   // 216  x 279  mm | 8.5  x 11.0 in`

and the **width** of **usLedger** 
`return CGSize(width: 720, height: 1224)  // 279  x 432  mm | 11.0 x 17.0 in`
should be 792 instead
`return CGSize(width: 792, height: 1224)  // 279  x 432  mm | 11.0 x 17.0 in`

when i specified the document size 
`document.layout = PDFPageLayout(size: CGSize(width: 612, height: 792),...`
the footer spacing was now properly aligned.

looks like an easy fix but i have never done pull requests before.. something new to learn
Sami

**Comment by philprime** [comment]
Hi Sami, thanks for letting me know about this issue!
Your fix looks correct and a PR would be great, therefore here a little tutorial:

1. Create your own fork of this repository by clicking on `Fork` in the top right corner, here on GitHub.
2. Clone the repository to your local machine, and preferably switch to the branch `develop` or a new branch based on `develop`
3. Apply, commit and push your changes to your repository.
4. Create a [Pull Request](https://github.com/techprimate/TPPDF/pulls) by clicking on `New pull request`
5. As the base select `techprimate/TPPDF` and the branch `develop`. As the head select your branch on your repository.
    5.1. If your repository is not showing up, you might have to click on `compare across forks`
6. Add a descriptive title, e.g. `#225: Fixing incorrect US page format heights` and more detail in the description. Also add `Closes #225` in the text, for smart reference

Mentioning the issue number will link the issue with the pull request.

**Comment by Sgkhour** [comment]
thank you for the primer... sorry for question but is it normal that i get an error that i can't write to tech primate/TPPDF and i should create my own sgkhour/TPPDF fork ? or is this a permission that you have to set ? tks

Sami

**Comment by philprime** [comment]
Fixed in 2.3.1
