### ISSUE TITLE
No Documentation for Table Generation

### ISSUE THREAD

**Issue by kishinmanglani** [techprimate/TPPDF#230]
There is no documentation for table generation. I have been using `generateCells`, but that seems to be deprecated

**Comment by kishinmanglani** [comment]
Need to use `.content` on table

**Comment by dipeshparashar** [comment]
@kishinmanglani  How to add data on table. Content only takes alignmentRows. What is the proper replacement to this ?

``` 
try eventTable.generateCells(
                data: eventRows ,
                alignments: aligmentRows )
```
