### ISSUE TITLE
Carthage build framework missing required keys

### ISSUE THREAD

**Issue by divyeshmakwana96** [techprimate/TPPDF#236]
I built the framework using Carthage but while uploading it to the TestFlight, I recieved the following error:

`This bundle Payload/Care Team.app/Frameworks/TPPDF.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion`

**Comment by philprime** [comment]
Hi there, can you please take a look at the branch ` hotfix/236-carthage-bundle-version` and let me know if it resolves the issue

**Comment by philprime** [comment]
This should be fixed with 2.3.2
I will close it now, if error still occurs please reopen
