### ISSUE TITLE
Table in Columns (or Table in Tables)

### ISSUE THREAD

**Issue by dipeshparashar** [techprimate/TPPDF#237]
Can you please suggest, what is the best way to achieve such a layout of tables in columns. Table in a table is breaking it and making it too complicated. 

![TablesInColumns](https://user-images.githubusercontent.com/8472277/95003007-0d69d500-05f8-11eb-8a73-50022d45b526.png)

**Comment by philprime** [comment]
Hi there, this kind of questions should be asked on StackOverflow as mentioned in [Communication](https://github.com/techprimate/TPPDF#communication)
