### ISSUE TITLE
Value of type 'PDFTable' has no member 'generateCells'

### ISSUE THREAD

**Issue by jigs777** [techprimate/TPPDF#239]
Please fixed the below issue:

"Value of type 'PDFTable' has no member 'generateCells'"

**Comment by AlexLojewski** [comment]
have anyone a solution of this problem or must techprimate fix it?

**Comment by chrisgonzgonz** [comment]
@jigs777 @AlexLojewski  It looks like #218 is the last release that uses the `generateCells` API. Table usage in subsequent releases is demonstrated here: 

https://github.com/techprimate/TPPDF/blob/master/Documentation/Usage.md#table

**Comment by philprime** [comment]
As @chrisgonzgonz (thank you), has mentioned, the PDFTable API has changed with the major release of TPPDF 2

`PDFTable.generateCells` does not exist anymore, but instead you can create a `PDFTable` with the correct size and set the data and alignment directly

**Comment by jigs777** [comment]
@chrisgonzgonz we are unable to set direct data to PDFTable.We are only set alignment directly.
like table.alignment.
Please if you have example so send it to me.
Thank you

**Comment by AlexLojewski** [comment]
thanks. i have solved the problem

**Comment by jigs777** [comment]
@AlexLojewski how to solve this problem?.

**Comment by jigs777** [comment]
@philprime any update on this.
