### ISSUE TITLE
shouldSplitCellsOnPageBeak is ignored

### ISSUE THREAD

**Issue by haemi** [techprimate/TPPDF#243]
I try to create a table where cells are not split on a page break. I stumbled upon the property `shouldSplitCellsOnPageBeak` which is `false` per default, so I would expect it to work as I like. But it seems the property is ignored.

When searching for that word, I only find it once, it seems as if it's never used... Is there a way to prevent cells to be split on page break?

**Comment by philprime** [comment]
Hi @haemi, which branch are you working on?

This is actually still a WIP in PR #223 so it's kind of weird the flag is already in a released version 🤔

**Comment by haemi** [comment]
Hi,

it’s there when I use the ‚pod try‘ or if I install it via SPM...

Best

Stefan

———————
+43 650 9255637
www.arkulpa.at

arkulpa GmbH
FN 418540 a, FB-Gericht: Landesgericht Feldkirch
Rheinstraße 27, 6890 Lustenau

**Comment by philprime** [comment]
Oh yes, I just checked out the master branch.
Looks like this was released in the most recent branch, as the flag already existed on `develop` but is not used yet.

Thanks a lot for reporting this!

**Comment by haemi** [comment]
is there a branch where I can use/test it? Urgently need this feature🙂

———————
+43 650 9255637
www.arkulpa.at

arkulpa GmbH
FN 418540 a, FB-Gericht: Landesgericht Feldkirch
Rheinstraße 27, 6890 Lustenau

**Comment by philprime** [comment]
You can take a look at branch `feature/205-optional-table-cell-splicing` if it already fits your needs, unfortunately due to time issues it might not be stable yet.

**Comment by haemi** [comment]
looks good, thanks a lot! The only problem left now is only that my cell is pretty wide, so an image can be too high to fit on one page - and I didn't find a way yet to make it smaller (when I make the `UIImage` itself smaller, the image in the table has the same size with less quality...)

**Comment by philprime** [comment]
Alright, merged and release in 2.3.2

The image resizing issue was mentioned in #251 so let's move that discussion over there, so this issue does not get polluted.

If the splitting cell issue still remains in the new release, please reopen.
