### ISSUE TITLE
PDFExternalDocument adds an empty page

### ISSUE THREAD

**Issue by divyeshmakwana96** [techprimate/TPPDF#247]
I recently tried the external pdf document api and it appears that it adds an empty page before.

       let document = PDFDocument(format: format)

        // meta data
        document.info.title = "Title"
        document.info.subject = "Subject"
        if let bundleName = Bundle.main.infoDictionary!["CFBundleName"] as? String  {
            document.info.author = bundleName
        }
        
        if let externalReportURL = Bundle.main.url(forResource: "Cover", withExtension: "pdf") {
            let coverDocument = PDFExternalDocument(url:externalReportURL, pages: 1)
            document.add(externalDocument: coverDocument)
        }
        
        let generator = PDFGenerator(document: document)
        try? generator.generateURL(filename: "report.pdf")

**Comment by philprime** [comment]
Hi there,

can you please take a look at the branch `feature/247-fixing-empty-external-page` and let me know if it resolves your issue.

**Comment by philprime** [comment]
Fixed in branch `develop`
