### ISSUE TITLE
Generator.totalPages does not count external documents

### ISSUE THREAD

**Issue by EliteTechnicalCare** [techprimate/TPPDF#248]
## What did you do?

Created a new pdf, added an external document with 150 pages. And generated the PDF

## What did you expect to happen?

for generator.totalPages to accurately reflect the number of pages

## What happened instead?

It claims there is only one page. This was working on an earlier version of tppdf

## TPPDF Environment

**TPPDF version:** 2.31
**Xcode version:**  12.1
**Swift version:** 5.x

## Demo Code / Project

ℹ Please add a code snippet, link to or upload a project we can download that reproduces the issue.
ℹ We need a fully compiling`PDFDocument`

**Comment by philprime** [comment]
Should be fixed in `feature/247-fixing-empty-external-page`. Please take a look and verify that the updated behavior is correct

**Comment by philprime** [comment]
Fixed in branch `develop`
