### ISSUE TITLE
Table is split too early to the next page

### ISSUE THREAD

**Issue by icarus31** [techprimate/TPPDF#249]
Hi,

I am using the latest 2.3.1 with merged code from feature/205.

With or without the merge, the table was always cut too soon leaving a big white space before continuing to the next page.

After checking the code, I found 'calculateBottomMaximum'. Is it possible the actual code below should be the one suggested? For sure, the new one works good for me.

Actual:

    internal static func calculateBottomMaximum(for generator: PDFGenerator) -> CGFloat {
        let layout = generator.layout
        let pageLayout = generator.document.layout

        return pageLayout.height
            - layout.margin.top
            - layout.heights.maxHeaderHeight()
    }

New:

    internal static func calculateBottomMaximum(for generator: PDFGenerator) -> CGFloat {
        let layout = generator.layout
        let pageLayout = generator.document.layout

        return pageLayout.height
            - layout.margin.bottom
            - layout.heights.maxFooterHeight()
    }

**Comment by philprime** [comment]
Hi there, yes this actually is the issue @lpeancovschi discovered too/fixed in #252

**Comment by philprime** [comment]
This should be fixed in 2.3.2 now. Please reopen if error still occurs.
