### ISSUE TITLE
Error when generating a table

### ISSUE THREAD

**Issue by d0hnj0e** [techprimate/TPPDF#257]
When trying to generate a simple table with

```
let row = table[row: 1]
row.content = [title]
```

the file `Swift/ContiguousArrayBuffer.swift`

```
public subscript(row index: Int) -> PDFTableRow {
        get {
            PDFTableRow(cells: self.cells[index], of: self, at: index)
        }
        set {
            self.cells[index] = newValue.cells
        }
    }
```

throws an error 

> Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444

**Comment by philprime** [comment]
Hi there, how did you initialize the table?

**Comment by philprime** [comment]
Closed due to inactivity
