### ISSUE TITLE
Swift 4.0

### ISSUE THREAD

**Issue by WillemPieterse** [Techprimate/TPPDF#26]
Good Day,

What is your intention wrt Swift 4.0? 
Just want to get my expectations in line with your planning 
👍

**Comment by nemecence90** [comment]
I converted the code through default Xcode swift 4.0 conversion and its seems to work just fine.

**Comment by techprimate-phil** [comment]
The branch `develop` is already in Swift 4.0, please refer to issue #29 for more informations
