### ISSUE TITLE
not able to build the app using pod file due to errors in class file

### ISSUE THREAD

**Issue by bhaveshlsamcom** [techprimate/TPPDF#265]
![Screenshot 2021-01-29 at 2 32 39 PM](https://user-images.githubusercontent.com/75381167/106254567-dec6d880-623e-11eb-86d7-cf82bebb4c1f.png)

**Comment by bhaveshlsamcom** [comment]
even tried adding source files but faced same errors

**Comment by philprime** [comment]
What Swift version are you using in your project?

**Comment by bhaveshlsamcom** [comment]
I am using Swift Version 4.2

**Comment by philprime** [comment]
To use the newest TPPDF version, at least Swift 5.2 is required (see [Requirements](https://github.com/techprimate/TPPDF#requirements))

**Comment by bhaveshlsamcom** [comment]
thank you for your support
