### ISSUE TITLE
Add image to only one column of a table

### ISSUE THREAD

**Issue by nemecence90** [Techprimate/TPPDF#27]
I have to generate a PDF where there are 7 text rows and there is one column which has image and caption. Is it possible to do so with current TPPDF implementation?

**Comment by techprimate-phil** [comment]
do i understand correctly, you want two columns, one with 7 text rows and one with just an image and a caption, next to each other?

**Comment by nemecence90** [comment]
You can check the picture, for what exactly I am trying to say.

![picture1](https://user-images.githubusercontent.com/3805632/32929258-c8af7a54-cb7c-11e7-9c22-da18abf21080.png)

**Comment by techprimate-phil** [comment]
Oh okay I understand now, you are teying the following:

1. Header cell spans two columns
2. Image with caption as cell content

1. is not in development yet, but definitely worth to look into. Shouldn‘t even be so hard, just time consuming
2. the new release of the develop branch is still unstable but is close to be done. That release will include images/captions as a table content.

**Comment by nemecence90** [comment]
@techprimate-phil Ok Buddy. Thanks a lot for the response. It's really a headache to achieve the pdf format. Are there any existing ways in which I can achieve this quickly?

**Comment by techprimate-phil** [comment]
No I am sorry, there is no existing way.
I am closing this for now, but I will reopen one issue for the column and row span.
