### ISSUE TITLE
Table cell border line color is not same

### ISSUE THREAD

**Issue by shawn736** [techprimate/TPPDF#275]
## What did you do?

Hi, I want to build a table pdf. 

## What did you expect to happen?

I expect the cell bottom line color is same black.

## What happened instead?

But, the cell bottom line color is not same. Some lines are light gray. Some lines are black.
![IMG_53C1759BDC42-1](https://user-images.githubusercontent.com/13273464/118581839-e6e25e00-b7c4-11eb-8e9e-85d3785bc70a.jpeg)

## TPPDF Environment

**TPPDF version: 2.3.5
**Xcode version: 12.5
**Swift version: 5.4

## Demo Code / Project

```
    table.style.outline = .none
    let tableCellStyle = PDFTableCellStyle(colors: (UIColor.clear, UIColor.black), borders: PDFTableCellBorders.init(left: .none, top: .none, right: .none, bottom: .init()), font: UIFont.boldSystemFont(ofSize: 12))
    table.style.rowHeaderStyle = tableCellStyle
    table.style.columnHeaderStyle = tableCellStyle
    table.style.contentStyle = tableCellStyle
    table.style.footerStyle = tableCellStyle
    table.style.alternatingContentStyle = tableCellStyle
```

**Comment by philprime** [comment]
thank you for reporting this bug.

I assume this issue is caused by <1.0 pixel line widths.
Can you please add the generated PDF too?

**Comment by philprime** [comment]
Closed due to inactivity
