### ISSUE TITLE
Add text wrapping options to Images

### ISSUE THREAD

**Issue by philprime** [techprimate/TPPDF#28]
When adding a single image there should be a way of defining how the image should fit in the text.

Following wrapping options should exist:

- Around                  --> Image is positioned freely and text should word wrap, so it is on all sides of the image
- Above and Below  --> Current behavior, previous element is on top of image, and the next element is below
- inline                      --> Next element is at the right side of the image
- background           --> Image is set at position but ignore by all elements, behind all elements
- foreground           --> Image is set at position but ignore by all elements, in front of all elements

**Comment by Gizmeondevwip** [comment]
how can i add a table with images and text in a row

**Comment by Gizmeondevwip** [comment]
how can i add a table with images and text in a row

[INNZUT2019048_20200728122012_20200728130611.pdf](https://github.com/techprimate/TPPDF/files/5246685/INNZUT2019048_20200728122012_20200728130611.pdf)

**Comment by Gizmeondevwip** [comment]
sample attached above

**Comment by icarus31** [comment]
@Gizmeondevwip , did you find a solution for your requirement? I would like to have that also. :-)

Thanks

**Comment by philprime** [comment]
Closing due to house-keeping. If this issue becomes relevant again, please reopen
