### ISSUE TITLE
iOS 15.0 Unable to archive build

### ISSUE THREAD

**Issue by grantespo** [techprimate/TPPDF#282]
CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target 'TPPDF' from project 'Pods')

...

remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
Command CompileSwiftSources failed with a nonzero exit code

**Comment by philprime** [comment]
Hi, thanks for opening the issue.

Can you please provide a few steps to reproduce this error?

**Comment by philprime** [comment]
Closed due to inactivity
