### ISSUE TITLE
A big release is coming up!

### ISSUE THREAD

**Issue by techprimate-phil** [Techprimate/TPPDF#29]
Many of you are asking about the following:

- Images/Attributed Strings in Tables
- Swift 4.0 Support
- more...

I am working a lot on the upcoming release of **1.0.0** where all these questions are answered.
Please stay with me, but keep it in mind!

I will put this in this issue so I can reference to it.

**Comment by marbetschar** [comment]
@techprimate-phil any approx ETA?

**Comment by techprimate-phil** [comment]
@marbetschar Preparing it right now, going to release now, as all elements are now working properly. More test cases and pixel testing will be necessary afterwards

**Comment by techprimate-phil** [comment]
Just released version 1.0.0
