### ISSUE TITLE
Table Outlines?

### ISSUE THREAD

**Issue by MatthewMerritt** [techprimate/TPPDF#290]
I have been using TPPDF in an older project for ever with version 1.2.1. I am able to use outlines on my tables as well as other styles have a nice looking for.

I have started another project now and using the latest version, but can't for the life of me get table outlines to work. Is anybody else having this issue? I have made a super simple table and can change all other styles.

**Comment by philprime** [comment]
Hi @MatthewMerritt thanks for opening up this issue.

Please use the bug report issue template and provide me with the following details:

- What did you do?
- What did you expect to happen?
- What happened instead?
- TPPDF Environment
  - TPPDF version
  - Xcode version
  - Swift version
- Demo Code

If you are able to show a screenshot what you expect vs what you got, that would be very helpful too. Thank you

**Comment by philprime** [comment]
Closed due to inactivity
