### ISSUE TITLE
conflicts with PDFKit. Getting error for PDFDocument.

### ISSUE THREAD

**Issue by javedmultani16** [techprimate/TPPDF#294]
In my intel base apple MacBook project working successfully I used TTPDF version 1.5.4, After that I am trying to run same project in new apple M1 chip.

I tried with various version of TTPDF. (even tried latest version)
I tried with rosetta mode of Xcode (Version 13.2.1 (13C100))

I am attaching screenshot here.

Old version of TTPDF 1.5.4

![Screenshot 2022-02-16 at 10 10 44 PM](https://user-images.githubusercontent.com/16849127/154314509-432d23e0-07a6-47a1-99b6-cf99dde511f7.png)

New version of TTPDF 2.3.5

![Screenshot 2022-02-16 at 10 10 15 PM](https://user-images.githubusercontent.com/16849127/154314491-e20c54f2-25bc-42ca-87cc-68de588c9c3a.png)

When try to jump on that

![Screenshot 2022-02-09 at 7 57 03 PM](https://user-images.githubusercontent.com/16849127/154315112-7f2172a3-cfff-4523-b5c2-a4fa5ed43c9d.png)

It seems to be conflicts with PDFKit.

**Comment by philprime** [comment]
Hi, yes this is conflicting with PDFKit (even tough TPPDF is older than PDFKit).

You can use both by adding a prefix `PDFKit.PDFDocument` and `TPPDF.PDFDocument`.

This should not be related to Intel vs M1

**Comment by javedmultani16** [comment]
Thanks ```TPPDF.PDFDocument``` works for me :)
