### ISSUE TITLE
Question: How to overlay on each page?

### ISSUE THREAD

**Issue by mazz** [techprimate/TPPDF#298]
Hi, I know about `set(_ container: PDFContainer, absoluteOffset: CGFloat)`

to overlay a large text item over a page. How to do this on each page? I want to “watermark” each page with the same text.

**Comment by philprime** [comment]
Hi, Watermarks have been requested in #231 and extensively discussed too, and there was an WIP pull request by @chrisgonzgonz #241 using a delegation pattern.

I will close this issue in favour of #231 so please read through what has been discussed there already. Will consider taking over the PR and finishing it myself
