### ISSUE TITLE
Image as background for every page

### ISSUE THREAD

**Issue by stefanovnt** [techprimate/TPPDF#303]
Hello,

Is it possible to set an image as background in every page?
I see there is an open issue regarding changing the color of the page, but not setting an illustration.

Probably would be nice to have the option to set it like:
document.background.image = UIImage..

**Comment by philprime** [comment]
Hi!

You should be able to that by creating a group of elements and setting it on `document. masterGroup`

**Comment by philprime** [comment]
Closed due to inactivity

**Comment by stefanovnt** [comment]
Hello @philprime! Thank you for your answer, I finally found the time to test your suggestion.
<sub>document.masterGroup</sub> seems working only with background color, but not with background images.

Here is the code I am trying:
`
        let pdfDocument = PDFDocument(format: .a4)
        pdfDocument.background.color = .blue
        
        let testGroup = PDFGroup(allowsBreaks: true, backgroundColor: .systemPink)
        testGroup.add(textObject: PDFSimpleText(text: "Hello,"))
        testGroup.add(textObject: PDFSimpleText(text: "World!"))
        
        if let imageData = UserDefaults.standard.object(forKey: DefaultPreferencesManager.pageBackgroundImage) as? Data,
           let backgroundImage = UIImage(data: imageData)?.withRenderingMode(.alwaysOriginal) {
            let pdfImage = PDFImage(image: backgroundImage, quality: 1.0, options: .none)
            //pdfImage.size = CGSize(width: 595, height: 942)
            testGroup.add(image: pdfImage)
            
            let masterGroup = PDFMasterGroup(isFullPage: true)
            masterGroup.backgroundImage = pdfImage
            //masterGroup.backgroundColor = .systemGray
            pdfDocument.set(master: masterGroup)
        }
        
        pdfDocument.add(group: testGroup)
        pdfDocument.createNewPage()
        pdfDocument.add(group: testGroup)
`
I added a pdf image to a PDFGroup in order to show that the image is loaded correctly.
When I use <sub>masterGroup.backgroundColor = .systemGray</sub> the background color (gray) is correctly displayed in every page behind the other containers, as expected.
I attached 2 screenshots, one with the background color and the other with the pdf image in the PDFMasterGroup.

Is this a bug or am I missing something?

![master-background-color](https://github.com/techprimate/TPPDF/assets/14198902/1ce62927-63af-4e8a-9994-1cf0ff9c7884)
![master-background-image](https://github.com/techprimate/TPPDF/assets/14198902/41abb19b-fa33-4857-a28d-6572a402eba8)
