### ISSUE TITLE
How to add UIView?

### ISSUE THREAD

**Issue by CodeSales** [techprimate/TPPDF#304]
Hello, I have a question that I would like to ask, please help to answer if it is convenient, thank you.

I want to add a UIView inside a PDF, this UIView has some UILabel on it.
I saw that there is no method for adding UIView in the interface, so I converted UIView into UIImage and added it.
But then the text of the UILabel on the UIView is very blurry.
Please help to see how to solve it, thank you.

**Comment by philprime** [comment]
Hi there,

TPPDF does not support rendering an UIView into an PDF, as it does not rely on UIKit or AppKit anymore, but mostly on CoreGraphics instead, and also because it uses building blocks instead of UI elements.

Rendering the UIView into an image, and then adding the UIImage is the best way to do it. If your UILabel is blurry, you might need to set a larger scale on the UIView before rendering.

Please provide a small reproducible example, so we can see how you approach it.

**Comment by DouYingOpen** [comment]
Hi, thank you very much for your reply.

Figure 1 is what I want to achieve.
Figure 2 is the effect I achieved using our project. The font is blurry.
Figure 3 is the code snippet.

What should I modify to make me display the high-definition Label.
Thank you~


`extension UIView {
    func asImage() -> UIImage {
        let renderer = UIGraphicsImageRenderer(bounds: bounds)
        return renderer.image { rendererContext in
            layer.render(in: rendererContext.cgContext)
        }
    }
}`

`let view = UIView.init(frame: CGRect.init(x: 0, y: 0, width: 500, height: 100))
        view.backgroundColor = .red
        let label = UILabel.init(frame: view.frame)
        label.text = "TestTestTestTestTestTestTestTest"
        label.textColor = .white
        view.addSubview(label)
        document.add(image: PDFImage.init(image: view.asImage()))
`
![1](https://user-images.githubusercontent.com/85730387/183010993-ef94857f-fe90-4685-83fc-f33cd1db8f63.jpg)
![2](https://user-images.githubusercontent.com/85730387/183011002-ef161adc-49b9-441e-878e-e33a429ef73c.PNG)
<img width="1680" alt="3" src="https://user-images.githubusercontent.com/85730387/183011009-c248a72d-5939-458e-9e26-bdb634e0c94c.png">

**Comment by CodeSales** [comment]
Thanks, I've solved the problem.

**Comment by kaaaaai** [comment]
> Thanks, I've solved the problem.

can you tell me how you solved it?
