### ISSUE TITLE
Footer separator line

### ISSUE THREAD

**Issue by peterhoucll** [techprimate/TPPDF#308]
I want to put a separator line at the top of the footer before the body of the footer. but the divider is not at the top, but at the bottom. 
How should I do this? 
Looking forward to your reply, thanks.

my code.
let line = PDFLineStyle.init(type: .full, color: .blue, width: 1.0)
document.addLineSeparator(.footerLeft, style: line)
document.add(.footerLeft, textObject: PDFSimpleText(text: "Footer Left"))

## TPPDF Environment

**TPPDF version:** 2.3.5
**Xcode version:**  14.1
**Swift version:** 5.2

**Comment by philprime** [comment]
Hi there,

can you please try to change the order of the statements?
The footer is in a bottom-to-top order, so you should be able to add the line after the text to get to your desired outcome
