### ISSUE TITLE
Add pages of other PDF file to document

### ISSUE THREAD

**Issue by philprime** [techprimate/TPPDF#31]
Given is a raw document and the data of a secondary PDF file.

One or multiple pages from another file can be added to the current PDF document.

**Comment by StefaniOSApps** [comment]
I would find it nice to be able to add or combine PDF files. Also a password protection etc. would be nice.

**Comment by EliteTechnicalCare** [comment]
Yes this would be great

**Comment by techprimate-phil** [comment]
As of now merging TPPDF documents is implemented, this issue was about including actual PDF pages from another flie

**Comment by EliteTechnicalCare** [comment]
Great work guys. Perhaps to implement other documents maybe create a method that would convert incoming pdfs to images on the fly and implement it in a PDFDocument. Perhaps thread it to prevent crashes on large pdfs/weak devices.

**Comment by techprimate-phil** [comment]
Actually I don't think we need to transform it into an image, as it should be possible to directly render a PDF into a CoreGraphics context

https://stackoverflow.com/questions/4639781/rendering-a-cgpdfpage-into-a-uiimage
https://developer.apple.com/documentation/coregraphics/cgpdfdocument

**Comment by sleekuser** [comment]
Hi @techprimate-phil, I came across implementing the same functionality. The API looks consistent with the rest of the methods. Thanks again for this library!! truly awesome

**Comment by philprime** [comment]
hi @sleekuser thanks for your feedback. I am merging it into develop right now
