### ISSUE TITLE
How do you refresh the PDF file?

### ISSUE THREAD

**Issue by brendand** [techprimate/TPPDF#310]
I'm building a screen in SwiftUI that lets me update parameters for the PDF report such as margins, orientation, row heights, etc. Basically putting a UI to many of the features of TPPDF into my app.

I've got the button, just like in the demo app to regenerate the PDF file. But the screen doesn't update when I re-run the `generatePDF()` function call. I've stepped through the debugger and I can see that my parameters are updated in the report building factory, but the screen just doesn't update. I looked around for a refresh or reload function, but I didn't find one.

Any suggestions?

Also I'm wondering if I really need to regenerate the whole report for some of these kinds of changes or can I just update the parameters on an existing PDFDocument / PDFTable? It could be much faster than looping through all of my model objects and rebuilding all the cells, etc.

**Comment by brendand** [comment]
The only way so far I've managed to refresh the report is to change the filename in the URL before generating the report.

**Comment by brendand** [comment]
Is there a better way?

**Comment by philprime** [comment]
A couple of things:

- Make sure to create a new `PDFGenerator` every time. As it keeps a state inside the object, it might interfere if you call `generate` multiple times.
- I do not know how you are displaying the PDF document in SwiftUI, but if you are reading it from the output URL, overwriting the same file content will most likely not trigger a SwiftUI view update, therefore not updating your screen. By writing it to a different file every time, you are also changing the SwiftUI state, which triggers the update
- `PDFDocument` is a mutable object used as a description of the final PDF document, which is not modified during generation. This means you can use all the provided functions to modify it, and simply put the updated in a generator. If you need more advanced access to the data structure inside `PDFDocument`, I would recommend creating a fork, and adding the functionality you need. Feel free to open up a PR afterwards, and we can consider adding it to the main repo.

**Comment by brendand** [comment]
- I am creating a new `PDFGenerator` every time I generate the report. I used your example SwiftUI implementation of your `generatePDF()` method as my starting point.
- Since I'm using your sample SwiftUI code, I'm displaying the PDF document the exact same way you are in the sample app.
- I'll look into the `PDFDocument` class to see what I'm able to modify there. But I guess I was thinking of things like changing page orientation or adjusting PDFTable cell alignments without having to regenerate the whole report by looping through all my data and rebuilding it.

For the refresh issue I just increment a counter now and append the counter to the end of the filename before the `.pdf` extension. Just before that I delete the previous report generation file so I don't clutter up the temp folder with all these PDF files.

**Comment by philprime** [comment]
Alright makes sense.

Another option would be creating a hash for the PDF file and store it in a @State, basically triggering a UI update only if the file content has changed.

**Comment by brendand** [comment]
I'm going to close this because now when I generate a new PDF file, I first delete the previous generated PDF file, then create the new one with an incrementing generation number. This causes the report to refresh.
