### ISSUE TITLE
Line separator in header that repeats for every page

### ISSUE THREAD

**Issue by brendand** [techprimate/TPPDF#312]
How can I get a line separator into my header so it repeats along with my report title on every page?

Here's my code so far:

```
document.add(.headerLeft, textObject: PDFSimpleText(text: reportSettings.reportTitle, style: headingStyle))
document.addLineSeparator(style: PDFLineStyle(type: .full))
document.layout.space.header = 20
```

I also want the header space before the content to appear after the line separator. But right now it's causing it to appear above the line separator.

**Comment by philprime** [comment]
> How can I get a line separator into my header so it repeats along with my report title on every page?

Not entirely sure how this should look like. Can you provide a mockup/example screenshot?

> I also want the header space before the content to appear after the line separator. But right now it's causing it to appear above the line separator.

This might be a bug. Please [enable debugging](https://github.com/techprimate/TPPDF/blob/master/Documentation/Usage.md#debug) and add a screenshot to the thread so we can see what it looks like with visible spacings

**Comment by brendand** [comment]
Ok, here's a couple screenshots to demonstrate the issue. The first page has a divider line below the report title. The second page shows it's missing. But also the divider line, because I'm not sure how to put it into the header, is part of the main content area, so it's not repeating. You can see the second page does not have the divider line. Plus, the divider line is not directly underneath the report title. There's a gap. I'd like the line to be directly beneath the report title and then the gap.

<img width="804" alt="image" src="https://user-images.githubusercontent.com/586075/205459493-d84f6046-ecd6-4319-a591-983fdf352992.png">

Here's the same page with debugging turned on, although the debugging makes it hard to see the divider lines:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/586075/205459560-62c014ea-71d0-4055-990c-4fd664add6f5.png">

**Comment by brendand** [comment]
It turns out you can specify the container when adding the line separator to the document, so just using this code works:

```
var headerAlignment = PDFContainer.headerLeft
switch reportSettings.headAlignment {
	case .center:
		headerAlignment = PDFContainer.headerCenter
	case .right:
		headerAlignment = PDFContainer.headerRight
	default:
		headerAlignment = PDFContainer.headerLeft
}
document.add(headerAlignment, textObject: PDFSimpleText(text: reportSettings.reportTitle, style: headingStyle))
document.addLineSeparator(headerAlignment, style: PDFLineStyle(type: .full))
```

I don't know how I missed this before. So now I have properly repeating lines in my headers.
