### ISSUE TITLE
Crash when generating report with zero rows other than the header row in a PDFTable

### ISSUE THREAD

**Issue by brendand** [techprimate/TPPDF#313]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with what info we expect. You can delete those lines once you've filled in the info.

## What did you do?

I was generating a report that had no table rows other than the header row.

## What did you expect to happen?

I expected the main header and header row of the table to get generated.

## What happened instead?

I encountered a crash at the following code in PDFTableObject of the calculate method.

```
var rowIdx = 0
while cells[rowIdx].allSatisfy({ $0.type == .rowHeader || $0.type == .header }) && rowIdx < table.size.rows {
          headerCells += cells[rowIdx]
          rowIdx += 1
 }
```

## TPPDF Environment

**TPPDF version:** 2.3.5 (master branch commit: 0dbe543c517c94d0bebacdaf1c0894a9a28c4a78)
**Xcode version:**  14.1
**Swift version:** 5.7

## Demo Code / Project

I think the solution to the crash is to short circuit the *while* loop by checking the `rowIdx` first:

```
var rowIdx = 0
while  rowIdx < table.size.rows && cells[rowIdx].allSatisfy({ $0.type == .rowHeader || $0.type == .header }) {
          headerCells += cells[rowIdx]
          rowIdx += 1
 }
```

That way the `cells[rowIdx]` expression won't get executed and won't crash

**Comment by brendand** [comment]
Or perhaps instead of checking `table.size.rows`, check against `cells.count` instead.

**Comment by philprime** [comment]
If the issue still remains, can you please provide a small reproducible example (incl. the document generation with data that crashes).
Otherwise please close the issue :)

**Comment by brendand** [comment]
I haven't actually forked the repo just yet. I'm using the Swift Package Manager to include it in my project, which makes the code read-only. I'll fork it and then try out the fix and if it works I'll submit a PR.

**Comment by brendand** [comment]
I submitted a pull request for this #316

**Comment by brendand** [comment]
Any chance of taking a look at it? It's just a small fix.
