### ISSUE TITLE
Image as NSTextAttachment gets lost

### ISSUE THREAD

**Issue by davidseek** [Techprimate/TPPDF#32]
Hey. I try to have an image attached into the NSAttributedString but the image gets lost.

```
        let pdf = PDFGenerator(format: .a4)
        
        let typeDetails = NSMutableAttributedString()
        let attachment = NSTextAttachment()
        attachment.image = Img.checked
        attachment.bounds = CGRect(x: 0, y: 0, width: 10, height: 10)
        let attachmentStr = NSAttributedString(attachment: attachment)
        
        typeDetails.append( NSAttributedString(string: ">>>>>") )
        typeDetails.append(attachmentStr)
        typeDetails.append( NSAttributedString(string: "<<<<<") )
        pdf.addAttributedText(text: typeDetails)
```

<img width="343" alt="screen shot 2017-11-03 at 2 25 28 pm" src="https://user-images.githubusercontent.com/17073950/32396540-dcc3cfa2-c0a2-11e7-8fb6-f726dcab7923.png">

I have tried several approaches as well as several images.

idea?

**Comment by techprimate-phil** [comment]
I didn't even know this was possible using NSAttirbutedString!

Definitely worth taking a look into it, maybe Core Text messes something up, we'll have to look up the documentations about more information.

Are you using the `develop` branch?
If so, we need to analyze the rendering algorithm in [PDFAttributedTextObject.swift](https://github.com/Techprimate/TPPDF/blob/develop/Source/Text/PDFAttributedTextObject.swift)

**Comment by davidseek** [comment]
Well it’s possible and ups the usage of your project by far since one it much more flexible in the usage of images. 

And no. I’m using the release branch. Should be master.

**Comment by techprimate-phil** [comment]
Okay, as I working on the develop branch right now for the big update explained in issue #29 I will put this on hold until the next release. 
Definitely looking into it.

**Comment by davidseek** [comment]
Any update?

**Comment by techprimate-phil** [comment]
I had a lot going on in the last few weeks, haven't got the time yet.

**Comment by davidseek** [comment]
if you want too, i can debug on that. would use the dev branch. but only if you assure me that no one else is working on it. dont want to waste my time.

**Comment by techprimate-phil** [comment]
I am not working on this yet, and nobody claimed to be working on it.
So yeah it would be great if you could figure out what is going on! Just fork the develop branch and create a pull-request afterwards, I will take care of pulling it back in

**Comment by davidseek** [comment]
will do. thanks

**Comment by davidseek** [comment]
Safe to say that this is not fixable.
My research endet with the knowledge that the `CGContext` removes the image for whatever reason. Even a bounty question on stack has not been able to find even a single helpful comment.

https://stackoverflow.com/questions/47745311/how-to-use-cgcontext-with-attributedstring-and-image-attachment

**Comment by techprimate-phil** [comment]
Looks like this is an issue we can't solve for now. I will mark it as ```wontfix```, maybe at some point we can fix this.

**Comment by omiz** [comment]
Is there any update on this missing NSTextAttachment issue?

**Comment by davidseek** [comment]
Hey @omiz I have moved away from this repository and to a java script solution.
It was simply not as flexible as I needed it. 
Sadly.

**Comment by smallqiang** [comment]
I have this issue too.
