### ISSUE TITLE
Info.plist file is missing the required key: CFBundleVersion (carthage | xcframework)

### ISSUE THREAD

**Issue by ArunPrasanth-R** [techprimate/TPPDF#329]
## What did you do?

Uploading exported __ipa__ file to appcenter. I'm using carthage with xcframework to build app.

## What did you expect to happen?

Upload exported __ipa__ file to appcenter without any issue.

## What happened instead?

Appcenter upload failed with below the error, **The Info.plist file is missing the required key: CFBundleVersion**

## TPPDF Environment

**TPPDF version:** 2.4.1
**Xcode version:**  14.2
**Swift version:** 5.7

## Demo Code / Project

{
    NSLocalizedDescription = "Asset validation failed";
    NSLocalizedFailureReason = "This bundle Payload/xx.app/Frameworks/TPPDF.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion (ID: 8e9e8a8b-275e-4f80-95ca-15ef9d977418)";

**Comment by philprime** [comment]
Please upload the `Info.plist` located in the `TPPDF.framework`

**Comment by ArunPrasanth-R** [comment]
![Screenshot 2023-05-22 at 09 49 49](https://github.com/techprimate/TPPDF/assets/5309451/a1d80bba-397e-4124-b45a-17b08ce1fe02)

**Comment by philprime** [comment]
I'll close this now, because this has not been reported since then.
If it is still relevant, feel free to reopen
