### ISSUE TITLE
FAIL to Compile 'develop' branch

### ISSUE THREAD

**Issue by StefaniOSApps** [Techprimate/TPPDF#33]
>> PDFTableObject.swift <<
FAIL: 
line 60: Binary operator '+' cannot be applied to two 'CGPoint' operands
line 70: Binary operator '+' cannot be applied to operands of type 'CGPoint' and 'CGFloat'

**Comment by techprimate-phil** [comment]
Resolved in commit [838179](https://github.com/Techprimate/TPPDF/commit/838179876991e5a3617d3084be679464da1b1b6f)
