### ISSUE TITLE
More customisations for pagination text

### ISSUE THREAD

**Issue by USBA** [techprimate/TPPDF#330]
It would be great to have more customisations for pagination text such as changing the font and changing the text color.

**Comment by philprime** [comment]
Thanks for opening up this issue. 
Even tough it's over a year old, I want to address this for future references.

The structure `PDFPagination`[https://techprimate.github.io/TPPDF/Structs/PDFPagination.html] has a property `textAttributes` which can be used to style the text similar to `NSAttributedString`.

This might have been excluded from the documentation in older version, but should now be available
