### ISSUE TITLE
[DEVELOP - BRANCH] PDFTableCellAlignment ## (SOLVED)

### ISSUE THREAD

**Issue by StefaniOSApps** [Techprimate/TPPDF#38]
Unfortunately only .left and .center work.
If I specify .right, the text will still be left justified.

**Comment by StefaniOSApps** [comment]
**.center works !**

![screen shot 2017-11-12 at 02 45 40](https://user-images.githubusercontent.com/29314643/32695154-eed4b9d8-c753-11e7-9212-883ec9f6c951.png)

**Comment by StefaniOSApps** [comment]
**.right doesn't work !**
![screen shot 2017-11-12 at 02 47 47](https://user-images.githubusercontent.com/29314643/32695155-eef01f7a-c753-11e7-8966-b0b53ba498a0.png)

<img width="364" alt="bildschirmfoto 2017-11-12 um 02 45 42" src="https://user-images.githubusercontent.com/29314643/32695156-ef08ed5c-c753-11e7-9a0f-9210c27b066e.png">

**Comment by StefaniOSApps** [comment]
can you add BUG Label?

**Comment by StefaniOSApps** [comment]
SOLVED (.right)

please replace:

```
let contentX: CGFloat = {
                    if alignment.isLeft {
                        return contentFrame.minX
                    } else if alignment.isRight {
                        return contentFrame.maxX - table.padding - contentFrame.width
                    } else {
                        return contentFrame.minX + (cellFrame.width - 2 * table.padding - contentFrame.width) / 2
                    }
                }()
```


WITH:

```
let contentX: CGFloat = {
                    if alignment.isLeft {
                        return contentFrame.minX
                    } else if alignment.isRight {
                        return contentFrame.minX + cellFrame.width - contentFrame.width - 2*table.padding
                    } else {
                        return contentFrame.minX + (cellFrame.width - 2 * table.padding - contentFrame.width) / 2
                    }
                }()
```

**Comment by StefaniOSApps** [comment]
PDFTableObject.swift

**Comment by techprimate-phil** [comment]
Thank you very much for your help. This should be fixed now!
