### ISSUE TITLE
[DEVELOP - BRANCH] missing automatic page break (table)

### ISSUE THREAD

**Issue by StefaniOSApps** [Techprimate/TPPDF#39]
As you may have noticed, the automatic page break does not work in the example table. That's why I'm opening these issues here.

**Comment by StefaniOSApps** [comment]
can you add BUG Label?

**Comment by techprimate-phil** [comment]
Fixed in commit [#c031886](https://github.com/Techprimate/TPPDF/commit/c031886e4c7aa586929a21ddd920610e6302df01)
