### ISSUE TITLE
Table Styles and single cell styling

### ISSUE THREAD

**Issue by AleksandarPetrov** [Techprimate/TPPDF#4]
I'd like to suggest a couple features to be implemented. 

- As user I want to set the background color of the cells. 
- As user I want to set the background color of the alternate row cells. 

Thanks

**Comment by Techprimate** [comment]
Great input!

I will take care of this feature in the upcoming days. I will create a table design class with default style values like Word or Pages and a way to modify single cells.

**Comment by AleksandarPetrov** [comment]
Thank you for the quick response, looking forward to this upgrade then.

**Comment by AleksandarPetrov** [comment]
Is there any reason to not have `lineBreakMode = .byWordWrapping` set as default for `paragraphStyle` in `drawText` method?

**Comment by Techprimate** [comment]
Have you encountered a visual difference when this value is set?

**Comment by AleksandarPetrov** [comment]
Unfortunately, no. My idea is to add a support for multi line text.

**Comment by Techprimate** [comment]
Please check Release 0.3.0 as this should support multiline text inside text cells

**Comment by Techprimate** [comment]
I just want to give a quick update, this feature is not completely done yet, but please checkout the feature branch https://github.com/Techprimate/TPPDF/tree/feature/issues/4/table_styles and let me know your thoughts

**Comment by Techprimate** [comment]
Merged in Release 0.4.0
