### ISSUE TITLE
Add custom View to pdf generator

### ISSUE THREAD

**Issue by Harshakvinu** [Techprimate/TPPDF#40]
Can you please try providing us the option to add views to pdf, if we want to add image or any other ui components in specified positions we want, we can add image to view and set its frame and then add view to pdfGenerator and its really useful and required.

Apart from that Great work Guys!!

**Comment by techprimate-phil** [comment]
If you want to add an image, there are commands to do so.
Checkout `addImage()`

What kind of views do you want to add to a document? The main idea behind TPPDF is creating PDF **Documents** as if it was created in a word processing software like e.g. Microsoft Word, Apple Pages or OpenLibre Office. Therefore this feature is not on the roadmap

**Comment by Harshakvinu** [comment]
Im working on an pdf report generating app and the UI design is something like the tagged image, if i could add uiView to pdf then this would be really help full
![screen shot 2017-12-05 at 6 43 08 pm](https://user-images.githubusercontent.com/17476358/33609000-60c4cc9a-d9ec-11e7-902b-fa539d25ed45.png)

**Comment by techprimate-phil** [comment]
Okay I do understand.

But still, it should be possible to create this PDF document without the need of UIViews. One way would be adding the image and add the description as the caption of the image. Then you can reset the offset position (distance to top edge) back to the top edge of the image and set the indentation to the image width. Then the "caret" position is at the top right position of the image and you can add the information, gallery images again as Image Objects, and then a text with the student name. After that, you reset the indentation so the text will be full width again and you can add all the PDF Data, it will fit the text content.

But I am sorry to disappoint you, not all features are yet stable, therefore if you still want it, you will have to use the _develop_ branch and work with the new API
