### ISSUE TITLE
Add row and column spanning in tables

### ISSUE THREAD

**Issue by philprime** [techprimate/TPPDF#41]
As mentioned in issue #27, it should be possible to let an item span over two columns.

## Issues found during brainstorming:
- Only specific cells have a column or row span, this messes up the row-based calculations, and the data validation

**Comment by grheza** [comment]
Is this issue or enhancemet in progress?

**Comment by techprimate-phil** [comment]
It is not due to time management. PR is welcome

**Comment by philprime** [comment]
well to bad I lost the whole branch need to restart working on this

**Comment by philprime** [comment]
Alright working on it in `feature/41-tables-spanning`

**Comment by philprime** [comment]
This will be fixed by #181, setting it on hold

**Comment by philprime** [comment]
Alright closing it, as this is available on the develop branch now
