### ISSUE TITLE
[Develop Branch] - orange horizontal lines

### ISSUE THREAD

**Issue by StefaniOSApps** [Techprimate/TPPDF#42]
Since the last update 3 orange horizontal lines are displayed. 

Debug mode ??

**Comment by techprimate-phil** [comment]
![screen shot 2017-12-06 at 21 28 49](https://user-images.githubusercontent.com/30923007/33683820-793b2072-dacc-11e7-8077-0d2a14759002.png)

Yes, these three orange lines are debug lines, indicating where the header area edge and the spacing between header and content. But I just realised I forgot to check if `debug` is enabled. Should be fixed now.

**Comment by StefaniOSApps** [comment]
perfekt !
