### ISSUE TITLE
[Develop Branch] - current Page Number

### ISSUE THREAD

**Issue by StefaniOSApps** [Techprimate/TPPDF#43]
My document has 4 pages:

```
document.setFont(.footerRight, font: UIFont(name: "Raleway-Light", size: 12.0)!)
document.pagination = PDFPagination(container: .footerRight,
                                            style: PDFPaginationStyle.customClosure(
                                                {(page, total) -> String in
                                                    return "\(page) | \(total)"
                                                }
        ))
```

On page 1: it displays: 1 | 4 - its O.K.
On page 2: it displays: 4 | 4 - its NOT O.K.
On page 3 it displays: 4 | 4 - its NOT O.K.
On page 4: it displays: 4 | 4 - its O.K.

plz add BUG Label

**Comment by StefaniOSApps** [comment]
Is it possible to use the font from the container .footerRight for the page navigation? The formatting is unfortunately not accepted.

**Comment by StefaniOSApps** [comment]
In another example, the document has 2 pages. On the 2nd page, only the header and one more line are displayed.

Page 1: page 1 of 1 - FAIL
Page 2: page 2 of 2 - FAIL

**Comment by techprimate-phil** [comment]
The reason this is failing is the following:

When creating a new page, the pagination element is calculated and added, therefore future elements are positioned correctly. And at the point of adding it is unknown how many pages there will be. Every pagination element is converted into a normal text object

One way would be, having a template, which is the longest the pagination string can get, e.g. "XXXX / XXXX" and after calculations this will be reset with the correct e.g. "123 / 5293" string, but this would result in a limit of 9999 pages.

Although 9999 pages is a very high number, it is a restriction. I can add that for now, by giving the pagination item an ID, and after calculations, before rendering, replacing all pagination items with the correct text. Should I do that or do you have an alternative solution?

**Comment by StefaniOSApps** [comment]
Unfortunately, the current page is not correct, this shows the first example:

On page 1: it displays: page 1 of 4 - its O.K.
On page 2: it displays: page 4 of 4 - its FAIL
On page 3 it displays: page 4 of 4 - its FAIL
On page 4: it displays: page 4 of 4 - its O.K.

It is a table.

The alternative would be that there are 2 calculations.
In the first calculation, the total number of pages is calculated. Although this would double the computation time, there would be no restriction on the page numbers. You could insert a dummy text here in the first calculation, like "xxxxx / xxxxx". This would take into account the height and width of the page number.

A dummy text would be unnecessary if you set the restriction to the container with footer or header. Thus, the page numbers would never be in the content area.
With this restriction, you would not change the document content in the first calculation. It would be a blank calculation to determine the total page numbers. In the first calculation, the PDFPagination would be ignored. Personally, I find this solution better.

**Comment by techprimate-phil** [comment]
Your solution is pretty much the same as mine. 
But i do not think the restriction would remove the need of a dummy text, as if something is added to the header/footer, it shrinks the available size of the content, because of the following calculation:

`availableHeight = pageHeight - topMargin - maxHeaderHeight - topSpacing - bottomSpacing - maxFooterHeight - bottomMargin` and the `topSpacing` are only subtracted if there is header and the same for `bottomSpacing` but with the footer

I think, if the pagination varies only in width, it wouldn't be a problem, as this does not affect the rest of the content. But if the pagination varies in height, this can cause the page breaking of elements.

**Comment by StefaniOSApps** [comment]
OK, this means that a while loop must be used to determine the maximum page number.

In the first run, the maximum page number is determined via dummy text. The page numbers are now placed in a local copy. The loop is re-run. If the maximum page number is larger, the local copy must be replaced. Now, the loop is re-run. The loop will abort if the maximum page number matches the previous value of the maximum page number.

This solution does not restrict the page number.
