### ISSUE TITLE
[DEVELOP-Branch] Get frame of object while creation

### ISSUE THREAD

**Issue by davidseek** [Techprimate/TPPDF#44]
is there any option for you to provide a public value to get the height of the table after filling it with the data array?

i need it to calculate whether or not i need a new page to prevent page break within content.
i'm using the develop branch to have the PDFTable object.

**Comment by StefaniOSApps** [comment]
you can use:

`BOOL isPageBreak = arrdata.count % (NUMBER_OF_ITEM_EACH_PAGE) as CGFLOAT > 1.0`

I think it should work.

**Comment by davidseek** [comment]
This will not work. Since my table view has dynamic cell content and the height of each cell varies.

**Comment by techprimate-phil** [comment]
All objects, including PDFTable, are converted into simpler elements like PDFAttributedTextObject, PDFImageObject when being calcuated, and then added to the elements list. 

Example: a 2x2 Table with 2 images and two words as content, will result in 2 PDFImageObjects, 2 PDFAttributedTextObjects, 4 PDFRectangleObjects for the background, 16 PDFLineObjects and so on

Every element has a `frame` property of type `CGRect`, so you can get the height values from there

**Comment by davidseek** [comment]
all right. i will look into it from the develop branch and see if i can create an open value. i think it’s likely that anyone else would appreciate a frane to work with

**Comment by techprimate-phil** [comment]
I understand, the PDFTableObject does have a `frame` to, but if a table is broken apart to multiple pages, one frame would not be enough.

**Comment by davidseek** [comment]
makes sense. i will see what i can do. i will try to figure it out for my case first and then check if there is sonething generic to create and contribute

**Comment by techprimate-phil** [comment]
Sounds good, putting this on hold, I might look into it as well

**Comment by techprimate-phil** [comment]
I will close this for now. Please reopen or create another issue if you necessary
