### ISSUE TITLE
[Develop Branch] - Upgrade to use in Objective-C

### ISSUE THREAD

**Issue by StefaniOSApps** [Techprimate/TPPDF#45]
is it possible to upgrade some func to use TPPDF in Objective C ?

**Comment by techprimate-phil** [comment]
According to [this stackoverflow](https://stackoverflow.com/questions/31884507/how-to-use-objective-c-cocoapods-in-a-swift-project) question, yes it should work fine.

**Comment by StefaniOSApps** [comment]
Yes, I know that. However, I can not access all features, including. the initiation of PDFDocument. I have now decided to save the data via NSUserDefaults and load and display it via external UIViewcontroller in Swift.

**Comment by StefaniOSApps** [comment]
You might be able to see the most necessary steps for Objectiv-C on the TPPDF homepage.

**Comment by StefaniOSApps** [comment]
i use a swift view controller... its O.K. :-)
