### ISSUE TITLE
Tables - Automatic column width, based on content

### ISSUE THREAD

**Issue by StefaniOSApps** [techprimate/TPPDF#46]
What about the idea of programming an algorithm that automatically sets the cell width in tables so that the height of the table becomes minimal.

**Comment by techprimate-phil** [comment]
Shrinking every column to a minimal width based on the content?
And then refine it using the algorithm so e.g. cells with only a few words get line breaks, and span over multiple lines and columns with bigger text paragraphs have therefore more width and are not as high as before anymore?

**Comment by StefaniOSApps** [comment]
Exactly!
It's about determining the optimal cell width for each column for different content, so the height of the table becomes minimal.
This feature would be great, right?

**Comment by philprime** [comment]
As it is now 2 years later, and I still do not have a use case for implementig this functionality, I will put in hold and close it for now, until it becomes relevant again
