### ISSUE TITLE
[DEVELOP BRANCH] Pointless TableView breaks

### ISSUE THREAD

**Issue by davidseek** [Techprimate/TPPDF#48]
I experience pointless TableView breaks whenever I put a tableView into a site that contains other elements.

If the TableView is after the first about 20% of page content, It gets cut of after the first row and the rest is on a new page:

<img width="417" alt="screen shot 2017-12-11 at 5 03 19 pm" src="https://user-images.githubusercontent.com/17073950/33861985-5d49f70e-de95-11e7-99cf-3d0e12abaeec.png">

If the table is on the first 20% of the page (means footer till 20% of the page frame from the top, the table is fine).
If the table start within the first 20% it is calculated correctly. For example: 

<img width="406" alt="screen shot 2017-12-11 at 5 05 49 pm" src="https://user-images.githubusercontent.com/17073950/33862019-8d5f9c46-de95-11e7-8c19-569cd29621c4.png">

But if the table start in the middle of the page, it is cut off for no reason after the first row:

<img width="427" alt="screen shot 2017-12-11 at 4 57 48 pm" src="https://user-images.githubusercontent.com/17073950/33862050-b4071018-de95-11e7-8d1a-85b7eeba6e03.png">

**Comment by davidseek** [comment]
The init of the table should be correct:

```
    func getTableWith(data: [[Any?]], alignments: [[PDFTableCellAlignment]]) -> PDFTable? {
        
        let table = PDFTable()
        
        do {
            
            try table.generateCells(data: data, alignments: alignments)
            
            let style = PDFTableStyleDefaults.simple
            style.outline = PDFLineStyle.none
            style.footerCount = 0
            style.columnHeaderCount = 1
            table.style = style
            
            return table
            
        } catch PDFError.tableContentInvalid(let value) {
            
            /*
             INVALID INPUT
             **/
            print("Invalid table content: " + String(describing: (type(of: value))))
            
        } catch let error {
            
            print("Error in: getTableWith: \(error)")
            CoreServices.catchError(error: error)
        }
        
        return nil
    }
```

**Comment by davidseek** [comment]
Latest dev branch with Swift 3

**Comment by techprimate-phil** [comment]
Closed to inactivity
