### ISSUE TITLE
Image as table cell content/data

### ISSUE THREAD

**Issue by jodymac** [Techprimate/TPPDF#5]
Just started using TPPDF and really like the it's design for ease of use.  I was hoping to generate a checklist report using this software, but I am falling just a hair short of a feature I need.

I would like to request an additional addtable that takes a uiimage as the first cell and a String as the second.

Or an offset that matches the top of the last previously placed element or an Offset that returns to the last place the offset was placed.  Like a marker. Trying to return to the offset location when I place dynamic test can leave me long or short on placing my next element in the container.

**Comment by Techprimate** [comment]
I am glad you like TPPDF, but unfortunately I am not sure what exact feature you are missing.

I know there is no way yet for placing an image in a table, if this feature would exist would it solve your problem?

**Comment by jodymac** [comment]
Yes, adding an image to the table would solve the problem.  I'm trying to have the picture be on the left and the notes they took on the right aligned to the top of the image.  The offset I mentioned above, you can disregard.
Thank you for your time, regardless of whether this moves forward from here!

**Comment by Techprimate** [comment]
as I am working on adding table styles for fixing issue #4 I will probably get a chance to dive into this and find a solution, propably supporting different types of table data

**Comment by jodymac** [comment]
That sounds great!  Thank you!

**Comment by chetem** [comment]
This is something I'm missing as well. Any chance you've made progress on this? I had a look at the table styling branch and am happy with how that's coming along! Would love to add images as well though :). 

Or as @jodymac mentioned, knowing the last offset at which something was drawn could also be helpful. For example, if I add an image to the pdf, what is the offset at which the next item will be drawn? This could be useful for overlapping items, especially if dynamically sized (like an arbitrary amount of text).

**Comment by Techprimate** [comment]
@jodymac I am working on multiple table content types right now. Next to text I will also add images as table content.

@chetem Please open a new issue for the drawing offset.

**Comment by Techprimate** [comment]
Please checkout the latest develop branch. Attributed strings and UIImages can now be content of a table
