### ISSUE TITLE
[DEVELOP BRANCH] Custom Path @ PDF Generator

### ISSUE THREAD

**Issue by StefaniOSApps** [Techprimate/TPPDF#55]
My problem is the following:
I am currently producing several PDF documents. The function for generateURL was modified by me. The PDF documents are created in a new temp folder. The folder will be converted to a ZIP file. Finally, the ZIP file will be exported.

Would it be possible to extend the function generateURL?

FROM 

`public static func generateURL(document: PDFDocument, filename: String, progress: ((CGFloat) -> Void)? = nil, debug: Bool = false) throws -> URL {`

TO 

`public static func generateURL(path: NSString, document: PDFDocument, filename: String, progress: ((CGFloat) -> Void)? = nil, debug: Bool = false) throws -> URL {`

TO USE

```
UIGraphicsBeginPDFContextToFile(path as String, document.layout.bounds, document.info.generate())
     try generator.generatePDFContext()
UIGraphicsEndPDFContext()
```

One could only ask if a custom path exits and then adjust the URL.

**Comment by techprimate-phil** [comment]
Are you proposing to give the generator a path it should write to? Why not copy the file from the temprorary folder after creation?

**Comment by StefaniOSApps** [comment]
Yes, I know that, of course. Unfortunately, this does not work as expected - despite several attempts. You would also have to delete the other files after copying. It would be nice if this export function could be extended. So, the custom file path is only used if one has been specified. This is a simple if-then story.

For me, the file paths are stored in an array and after all PDF files have been generated, the ZIP file will generated.

**Comment by techprimate-phil** [comment]
I have added a `generate(document: document, to: url)` method, which renders the document directly to the provided url and does not return a temporary URL. I hope this fits your needs

**Comment by StefaniOSApps** [comment]
perfekt.. thanks 👍 🥇
