### ISSUE TITLE
Custom PDF Metadata fields

### ISSUE THREAD

**Issue by marbetschar** [techprimate/TPPDF#60]
Is it possible while using TPPDF to read/write extended PDF metadata? I'm thinking of adding support for ZUGFeRD standard for invoicing. Here an example of how the code may look like in Java:

https://konik.io/docs/

**Comment by techprimate-phil** [comment]
At the moment the [these](https://developer.apple.com/documentation/coregraphics/cgcontext/auxiliary_dictionary_keys) metadata keys are available.

Can you create a summary of what metadata key/value types you need to to support your functionality? Maybe we need to create a custom PDF metadata engine which manipulates the bytes of the created PDF file

**Comment by marbetschar** [comment]
I see.  ZUGFeERD is a Standard for processing invoices automatically. That said at it‘s core is a simple XML specification which is embedded within a PDF.

I‘m aware that as of now there are a multitude of such standards available. Therefore, from a TPPDF point of view it may be enough to allow read/write any custom meta data through a Data attribute...?

**Comment by techprimate-phil** [comment]
Looks like we need to find a way of changing the metadata of the generated PDF file. I do not know the PDF specification enough to know, but I do know there is no way to add any other metadata other than the before mentioned auxilliary keys.

**Comment by marbetschar** [comment]
Got it. Isn't a high priority on my end as of now just wanted to know if this is already possible.

**Comment by techprimate-phil** [comment]
I just found this method in the documentation:

[CGContext.addDocumentMetadata(_:)](https://developer.apple.com/documentation/coregraphics/cgcontext/1456026-adddocumentmetadata)

Do you think we can create the XML metadata using this method on the PDF context?

**Comment by philprime** [comment]
Is still a relevant issue? Otherwise I will close this for now and we will take a look at PDF Metadata if there is a actual use-case to work with.

**Comment by philprime** [comment]
Closed due to inactivity
