### ISSUE TITLE
PDFTableCell: public constructor & .copy

### ISSUE THREAD

**Issue by marbetschar** [Techprimate/TPPDF#64]
Is there a specific reason why the `PDFTableCell` constructor is not `public`?
https://github.com/Techprimate/TPPDF/blob/83f39173c65132b06a65e3c89c0a220f3516a129/Source/Table/PDFTableCell.swift#L14

And it would also be awesome beeing able to `copy` an existing `PDFTableCell`.

My use case is as follows:
I have a table presenting line items which consist of a predefined list of cell styles (e.g. article name is bold and left aligned, price is regular and right aligned). Now I'd love to initialize template cells which can simply be copied during the table generation process.

In the end, I'll then assign all generated cells to `table.cells`.

**Comment by techprimate-phil** [comment]
No, i just checked and it seems to be a mistake, as the example only works with `table.generateCells` and therefore didn't require a public constructor. I even mentioned the possibility of directly modifying `table.cells`. Fixing it right now, will be in upcoming release
