### ISSUE TITLE
Atrributed String - Underline is not working

### ISSUE THREAD

**Issue by marbetschar** [Techprimate/TPPDF#65]
Setting `.underlineStyle` to `NSUnderlineStyle.styleSingle` results in a Crash.

Can you please fix this? Unfortunately I was not able to figure out what exactly needs to be done to get this running. Maybe this is related to https://github.com/Techprimate/TPPDF/issues/61

**Comment by techprimate-phil** [comment]
you need to use `NSUnderlineStyle.styleSingle.rawValue` as it is expecting a `Int` as value. This works:

```swift
        let title = NSMutableAttributedString(string: "TPPDF", attributes: [
            .font: UIFont.boldSystemFont(ofSize: 50.0),
            .foregroundColor: UIColor(red: 0.171875, green: 0.2421875, blue: 0.3125, alpha: 1.0).cgColor,
            .underlineStyle: NSUnderlineStyle.styleSingle.rawValue,
            .paragraphStyle: paragraph
            ])
```
