### ISSUE TITLE
Two layouts: First page and following pages

### ISSUE THREAD

**Issue by marbetschar** [Techprimate/TPPDF#66]
I'm currently working on invoice pdf generation which conforms to [DIN 5008 Form B](https://de.wikipedia.org/wiki/DIN_5008#/media/File:DIN_5008_Form_B.svg) - this works very vell.

One of the last challenges I'm facing now is: I'd love to output the logo on the first page in the upper right corner (max 35mm in height, having a top-margin (defined in layout) of 10mm which totals in a heading height 45mm, which is the max height allowed according to the specs).

If the invoice now spawns over multiple pages, I don't want to repeat the logo in the upper right corner - and I also want to increase the top-margin of the layout to 20mm. Outputting text with a top-margin of 10mm simply does not look nice.

How can I achieve the desired result? First thing which comes into my mind would be the ability to define two layouts: one for the first page and one for all following pages.

Sidenote: It's the first time in my career I work with a PDF generation framework which works that smooth and intuitively - thank you so much for all the work you put into TPPDF, I really appreciate!!

**Comment by techprimate-phil** [comment]
Do you think it is possible to add the image on the first page using `addImage` and setting a negative top offset? Or is this too hacky?

Having a special cover page would be possible, but we should keep TPPDF as generic as possible. What if we add a way of merging two PDFDocuments to one? One document would be calculated as you desire for the cover, and the second document is the actual content. Each one is calculated individually and then during the render process it is drawn into a single PDF file

**Comment by marbetschar** [comment]
Setting the image using a negative top offset should do the job for my use case, wasn't aware of this possibility. Seems like the easiest solution as for now.

In cases of a special cover page: I like the approach of being able to merge multiple documents together - as this would also allow more advanced scenarios such as having one (or more) horizontal pages within a document etc.

**Comment by techprimate-phil** [comment]
Exactly. I propose we close this issue for now, as the negative top offset solves your problem, and reopen a new issue about merging documents
