### ISSUE TITLE
Image resizing does not work as expected

### ISSUE THREAD

**Issue by marbetschar** [techprimate/TPPDF#69]
In my invoice generation process I'd love to render a logo in the upper right corner. According to the [DIN 5008 Form B specs](https://de.wikipedia.org/wiki/Datei:DIN_5008_Form_B.svg) there are 45mm reserved on top of the first page to design a custom header.

However, if I use the following code I run into two issues:

1. the image is not right aligned
2. the image is not resized as expected

```
document.addImage(.contentRight, image: PDFImage(
	image: logo,
	caption: nil,
	size: CGSize(
		width: document.layout.size.width - document.layout.margin.left - document.layout.margin.right,
		height: pointsPerMillimeter * 30
	),
	sizeFit: .height,
	quality: 1.0)
)
```

Here's a screenshot of the output I get:
![img_ac4f31bf488d-1](https://user-images.githubusercontent.com/392542/39807593-fadcd444-537c-11e8-822a-ae71c1102940.jpeg)

Sidenote: As you can see I had to calculate the contentSize manually - can we add public access to `document.layout.contentSize`?

**UPDATE:** For my use case it would be even better if we could align the image `.topRight`. This way the user is able to select whichever size of image he wants and it will be scaled proportionally from the topRight to the lowerLeft - while it is guaranteed the image fits into the defined container (contentSize.width * 30mm). Maybe this should be the default behaviour for `.addImage(.contentRight, ...` anyways?

**Comment by philprime** [comment]
Hi there, a lot of time has passed since this issue has been created.
I'll close it for now, if it still relevant, please feel free to reopen it
