### ISSUE TITLE
Attributed Strings in Table

### ISSUE THREAD

**Issue by abataille** [Techprimate/TPPDF#7]
Is there a way to have attributed strings in a table ?

**Comment by Techprimate** [comment]
There is no way for now, but a pull-request is always appreciated. 
Table styling is currently in development and more information are in issue #4

**Comment by Techprimate** [comment]
With version 0.4.0 table styling was introduced. If this does not fulfil your expectations please reopen this issue.

**Comment by nemecence90** [comment]
I need to have bold and italic texts in table columns and i guess this does not fulfill that. Can you please give a example as to how do we add attributed texts in table columns like 
[[NSAttributedString]] instead of [[String]]?

**Comment by USBA** [comment]
+1

**Comment by USBA** [comment]
Hi all, 
Is there any way to add bold text inside a table?
My requirement is I need to make the text in column headers bold.

**Comment by philprime** [comment]
@USBA you can configure a bold font on the `PDFTable` as defined in the [documentation](https://github.com/techprimate/TPPDF/blob/main/Documentation/Usage.md#cell-style)

Example:

```swift
let document = PDFDocument(format: .b5)
let table = PDFTable(rows: 4, columns: 2)
table.content = [
    ["Index", "Name"],
    [1, "Waterfall"],
    [2, "Forrest"],
    [3, "Fireworks"],
]
table.style.columnHeaderStyle.font = .systemFont(ofSize: 15, weight: .black)
document.add(table: table)
```

<img width="433" alt="Screenshot 2024-06-23 at 11 09 27" src="https://github.com/techprimate/TPPDF/assets/30923007/d521a662-9c30-42a5-a1d1-d5365790aef5">
