### ISSUE TITLE
PDFImage quality does not work as expected

### ISSUE THREAD

**Issue by omiz** [Techprimate/TPPDF#78]
From the documentation:

>      /**
>      JPEG quality of image.
> 
>      Value ranges between 0.0 and 1.0, maximum quality equals 1.0
>      */
>      public var quality: CGFloat

But the current behaviour is 

- 0 will not apply any compression
- 1 will apply compression
- values in between behave correctly as the documentation

expected behaviour
- 0 will have the most compression or least quality 
- 1 will have the least compression or full quality (no compression)

**Comment by techprimate-phil** [comment]
Fixed in release 1.1.2

**Comment by omiz** [comment]
just a question: so `zero` wasn't adding any compression before right. 
what about making it an `optional` and if it's nil then no compression and if `some` then it has some?

**Comment by techprimate-phil** [comment]
The image is resized in any case to fit the given frame, therefore TPPDF has to calculate and convert anyway. 
Making it an `Optional` would require us to set a fallback value, which is `1.0` to have the best quality/least compression. If we require the developer to set the quality explicitly, it is easier to understand what this value does.

**Comment by omiz** [comment]
this is not exactly what I want 
I still prefer to have no compression at all for some images

there was this code that makes `zero` without any compression

`if resizeFactor == 0 { return image }`

I don't see why we can't make it optional with 

`if resizeFactor == nil { return image }`

sorry I didn't read the full implementing so it will be something like that I hope you know what I mean

**Comment by omiz** [comment]
lets not make it complicated.

if you get any image needs resizing resizing then do it.
if you get a quality (not nil) then add a compression.

in my case I sometimes need to crop, resize and keep ratio, stretch. so it's not about the resizing process but more about not losing the quality in some of the images.

So if resized the image already then resizing it again will mean extra un-needed work.
if I don't want to compress the image and don't care about the size of some images then I can pass nil for the quality and will not be changed.

I don't see the need of adding any extra option.

But if you really really want to do this `PDFImageOptimisation` then here is a suggestion take it or leave it

```
struct PDFImageOptimisation: OptionSet {
    
    let rawValue: Int
}

extension PDFImageOptimisation {
    
    static let resize = PDFImageOptimisation(rawValue: 1 << 0)
    
    static let compress = PDFImageOptimisation(rawValue: 1 << 1)
}

var options: PDFImageOptimisation

options = [.resize, .compress] // all

options = .resize // single

if options.contains(.resize) {
    // do resize
}
```

**Comment by techprimate-phil** [comment]
So it is about not modifying the image if not necessary. Sounds reasonable.

I like the `OptionSet` approach as it gives precise control with high readability.
I will implement this and release an update.
The default options will be `[.resize, .compress]` therefore it won't change existing documents.

**Comment by techprimate-phil** [comment]
Can you please take a look at the latest commit in the develop branch and let me know about your thoughts.

**Comment by omiz** [comment]
You did a great job thank you man!

Just a small question: do you think that it might be better to separate the implementation of resize and compress? 

Here is what I mean

instead of this:
`static func resizeAndCompressImage(image: UIImage, frame: CGRect, shouldResize: Bool, shouldCompress: Bool, quality: CGFloat) -> UIImage`

use this:

```
static func resize(image: UIImage, frame: CGRect, quality: CGFloat) -> UIImage {
    
    let factor: CGFloat = min(3 * quality, 1)
    
    let resizeFactor = factor.isZero ? 0.2 : factor
    
    let size = CGSize(width: frame.width * resizeFactor, height: frame.height * resizeFactor)
    
    UIGraphicsBeginImageContext(size)
    
    image.draw(in: CGRect(origin: .zero, size: size))
    
    let finalImage = UIGraphicsGetImageFromCurrentImageContext()
    
    UIGraphicsEndImageContext()
    
    return finalImage ?? image
}

static func compress(image: UIImage, quality: CGFloat) -> UIImage {

    guard let data = UIImageJPEGRepresentation(image, quality) else { return image }
    
    guard let compressed = UIImage(data: data) else { return image }

    return compressed
}
```

so it can be easily used as a different action and it will be scalable (if someone asked for crop action os something else)

**Comment by techprimate-phil** [comment]
Great input! Thank you! I am preparing a release 1.2.0 right now, going to be available soon!
