### ISSUE TITLE
TableCellAlignment not working in multi-line table cells

### ISSUE THREAD

**Issue by caloon** [Techprimate/TPPDF#8]
I found that setting TableCellAlignments for cells inside a table is not working properly when the text within the cell is longer than one line.

See screenshots: 
- the one-line bottom line aligns perfectly [right, right, center, center, left - for demo purposes]
- all two-line headline seem to align to .center, but I suppose it only aligns the frame of the text inside the cell and not the text itself (NSTextAlignment). Since attributed strings don't work, this is an issue for me.

![screen shot 2017-03-01 at 09 20 59](https://cloud.githubusercontent.com/assets/1286053/23451499/710337e4-fe60-11e6-8e8e-9dee25744246.png)
![screen shot 2017-03-01 at 09 21 06](https://cloud.githubusercontent.com/assets/1286053/23451500/71284ce6-fe60-11e6-931b-fc54cd8cb9f7.png)

**Comment by Techprimate** [comment]
Sorry for not responding sooner, i will investigate this and try to figure out whats going on.

**Comment by techprimate-phil** [comment]
Resolved in commit #56b009
