### ISSUE TITLE
remove dash border

### ISSUE THREAD

**Issue by eitanaviv** [Techprimate/TPPDF#80]
Hey, 
Is it possible to remove the dash border from the elements? 
including those on the sides
https://imgur.com/a/jGFEf0R

**Comment by eitanaviv** [comment]
Thanks for answer to my email. 
Helped my a lot!

**Comment by emericspiroux** [comment]
I think peoples said « set debug mode to false » but I put a comment for futur :)

**Comment by techprimate-phil** [comment]
Yes, the dashed border is a debug overlay.
