### ISSUE TITLE
how do i set table cell height,

### ISSUE THREAD

**Issue by waiwaib** [Techprimate/TPPDF#84]
hello, I really like your TPPDF. but i can't find any way to set cellHeight at table, Please tell me if there any way to set table cell height,
Best Regards
Evan he

**Comment by waiwaib** [comment]
Exactly,when i try table.generateCells data contains Image, the image size is  <14X14>,but when cell generated,the image content are more bigger than it's original size, so i want custom set it's size....is there an bug at automatic table cell height calculation?

**Comment by waiwaib** [comment]
I found how to deal with table cell height problem...thanks

**Comment by ElnazTaqizadeh** [comment]
> I found how to deal with table cell height problem...thanks
@waiwaib Could you please share how did you change the cell height?
