### ISSUE TITLE
addLineSeparator doesn't work in header

### ISSUE THREAD

**Issue by protspace** [techprimate/TPPDF#88]
Want to say that the library is great!

I noticed that 
           ` document.addLineSeparator(.headerCenter, style: PDFLineStyle(type: .full, color: UIColor.black, width: 2))
`
puts line in random positions except first page. And for some pages it not shown at all

**Comment by techprimate-phil** [comment]
Seems like the frame calculations for the line separator might be off.
Can you take a look at what is calculated and what would be the correct value?

**Comment by bigfish2001** [comment]
Looks like it does not work in footer either.  I don't think the override func calculate(generator: PDFGenerator, container: PDFContainer) throws -> [(PDFContainer, PDFObject)] method is calculating y position off of the container.  I just started looking at this code so I have not seen the proper way to fix this.

**Comment by techprimate-phil** [comment]
This should be fixed in the develop branch. Please confirm

**Comment by techprimate-phil** [comment]
Closed due to inactivity, please reopen if it reoccurs
