### ISSUE TITLE
Support for Swift 4.2 and Xcode 10 ??

### ISSUE THREAD

**Issue by techmehra** [Techprimate/TPPDF#91]

**Comment by anilabsinc-ajay** [comment]
Any update on this... @Techprimate

**Comment by anilabsinc-ajay** [comment]
@rodrigosmarques This is Temporary solution but we are looking for the permanent.

**Comment by techprimate-phil** [comment]
I am sorry for the long delay, there has been lot going on. I will take care of migration to swift 4.2 today

**Comment by techprimate-phil** [comment]
Please checkout release 1.3.0, should support Swift 4.2 and Xcode 10

**Comment by shial4** [comment]
@techprimate-phil 

[!] CocoaPods could not find compatible versions for pod "TPPDF":
  In Podfile:
    TPPDF (~> 1.3.0)

None of your spec sources contain a spec satisfying the dependency: `TPPDF (~> 1.3.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
