### ISSUE TITLE
Cocoapodas 1.3.0

### ISSUE THREAD

**Issue by shial4** [Techprimate/TPPDF#95]
I am on recent cocoapod version.
Using TPPDF (1.2.1)

[!] CocoaPods could not find compatible versions for pod "TPPDF":
In Podfile:
TPPDF (~> 1.3.0)

None of your spec sources contain a spec satisfying the dependency: TPPDF (~> 1.3.0).

You have either:

out-of-date source repos which you can update with pod repo update or with pod install --repo-update.
mistyped the name or version.
not added the source repo that hosts the Podspec to your Podfile.
Note: as of CocoaPods 1.0, pod repo update does not happen on pod install by default.

**Comment by shial4** [comment]
@techprimate-phil can you look into it?

**Comment by techprimate-phil** [comment]
Version 1.3.0 is released as you can see [here in the CocoaPods Spec Repo](https://github.com/CocoaPods/Specs/commit/26049161ec01c397d90b3b7d81e53147e14ed738)

Did you try to update your specs-repo as written?

**Comment by shial4** [comment]
I did.

**Comment by shial4** [comment]
My Podfile look as follows:

```
project 'Demo.xcodeproj'
platform :ios, '10.0'
use_frameworks!

def main_dependencies
    pod 'SWindow', '~> 0.1.11'
    pod 'SLazeKit', '~> 0.2.2'
    pod 'SLazeCoreData', '~> 0.1.3'
    pod 'HEREMaps', '~> 3.7.0'
    pod 'GoogleAnalytics', '~> 3.17.0'
    pod 'TPPDF'
end

target 'Demo' do
    main_dependencies
end

target 'Tests' do
    main_dependencies
end
```

**Comment by shial4** [comment]
Must be something work with cocoapods, I did that before. 
It does work with a new project. However, it can't update the version with my old one. :< no clue what's wrong in there

**Comment by shial4** [comment]
Remove pod's installation and redoing action fixed the problem
