### ISSUE TITLE
Table cell with two column layout

### ISSUE THREAD

**Issue by benrudhart** [techprimate/TPPDF#96]
Hi there,

Is there a way to configure the cells of a table view with a custom layout:
I'd like to display two labels where the left one is left aligned and the right one is right aligned.

If that option is not given: How can I create it myself?
Thank you

**Comment by benrudhart** [comment]
Update/ Addition: How can I use a custom view/ content in a table cell?
Guess I need to draw it myself - is that possible?

**Comment by techprimate-phil** [comment]
### Question 1)

```swift
try table.generateCells(data: [
        ["Left value", "Right value"],
    ],
    alignments: [
        [.left, .right],
    ])
```

Does this fit your needs? (Code is untested and taken from README)

### Question 2)

What kind of custom content do you want to render?
Currently these types are supported (from README):

> - PDFTableContent.none, empty cell
> - PDFTableContent.string, a simple string only styled through the cell style
> - PDFTableContent.attributedString, an attributed string which won't be changed by the cell style
> - PDFTableContent.image

There is no possibility for now to add custom content, as it requires frame calculations and rendering. If you propose a type which has more usage cases than yours, I am happy to see a PR.

**Comment by benrudhart** [comment]
Thank you. Unfortunately it doesn’t help.
Q1)
 That’s already what I did. But by using this layout the left and right cell (also in all subsequent rows) will have the same width which is not what I want
Q2)
The desired layout (of Q1) would rather be two labels next to each other that could always use the whole width (except an inter-label padding). But I’d also need to setup the content compression resistancy of the cells, and multi-line/ truncating setup. I guess my requirements are too custom.
That’s why I was asking for a more generic solution.

Any ideas how I could get there?

**Comment by techprimate-phil** [comment]
Hi @benrudhart is this issue still relevant?

**Comment by benrudhart** [comment]
yes!

**Comment by techprimate-phil** [comment]
I'll try to rephrase your Answer to Q2, to see if I do understand your use case:

1. Two labels next to each other
2. Both labels use the whole width of the page (with inter-label-padding)
3. Both labels are using content compression resistance to calculate their width
--> width is dynamic based on content and not a fixed value
4. Each label should truncate/line break their text on their own

**Comment by benrudhart** [comment]
Hi again,
I think the most comfortable way (for me) would be to have access to these labels in order to set up compression resistance/ number of lines/ font/ line breaking mode/ text alignment etc.

Basically I need two labels in one cell (regarding 2: no, not the whole width of the page but of the cell).

On the other hand it might come in handy if I could simply provide any custom view that will be added to the cell. Maybe that's even easier for you?!

**Comment by techprimate-phil** [comment]
TPPDF has the following (simplified) logic:
- When adding elements to a document, it generates a list of elements.
- Calculate the frame of each element.
- Render all elements in their calculated frames.

Complex elements like tables are simple a collection of line-, text- and image elements.

Would be hooking into the calculations be a working solution?

Personally I would prefer to not use custom views, as without it would be easier to create an own PDF render engine (and not using CGPDFContext) at some point in the future. Thats one of the reasons why this library offers only basic/easy-to-use methods on a high abstract layer.

**Comment by benrudhart** [comment]
Sorry for the late answer. Right now I'm not working on this but will probably do again in the future. Will let you know if there's anything that could help me. Thank you for your support.

**Comment by philprime** [comment]
I will close this for now, either reopen or create a new issue if necessary
