### ISSUE TITLE
I can't manually install the framework

### ISSUE THREAD

**Issue by AClmbr** [Techprimate/TPPDF#97]
Hi,

I have to manually install the framework, but I'm having problems with this.

I followed the instructions, but when I add
`import TPPDF`
I get
`No such module 'TPPDF'`

I think the README file may be outdated.
First I added the module as a submodule of my repo. Then I dragged the Pods.xcodeproj into my project. When I clicked on the `+` under the "Embedded Binaries", I had the choice between 5 frameworks:

- Nimble.framework,
- Pods_TPPDF_Example.framework,
- Pods_TPPDF_Tests.framework,
- Quick.framework,
- TPPDF.framework.

I selected TPPDF.framework, but no way, I got the error mentioned above.

Do you have an idea why?

Thanks in advance!

**Comment by techprimate-phil** [comment]
TBH I haven't really worked with manual installations before, as I prefer Cocoapods to do the configuration.
Try comparing your project configuration with a Cocoapods project and check for differences. 
Would be great if you could create a PR with an updated README

**Comment by AClmbr** [comment]
I finally tried with Cocoapods and it worked. So I don't have the solution for the manual installation, sorry :/

**Comment by techprimate-phil** [comment]
At least it works now!
