### ISSUE TITLE
Dotted lines 

### ISSUE THREAD

**Issue by raphdaff** [Techprimate/TPPDF#99]
Hi there,

.. how do I get rid of those red or blue dotted lines around textElements, at margins etc in the generated file?

thx

**Comment by raphdaff** [comment]
..sry. silly question. it is the debug mode:

   url = try PDFGenerator.generateURL(document: document, filename: "Example.pdf", progress: {
                (progressValue: CGFloat) in
                print("progress: ", progressValue)
            }, debug: false)

thx anyway.

**Comment by techprimate-phil** [comment]
Duplicate of #83
